const API_BASE = '/api';

const state = {
  route: location.hash.slice(1) || 'home',
  theme: localStorage.getItem('ss-theme') || 'light',
  lang: localStorage.getItem('ss-lang') || 'ar',
  user: JSON.parse(localStorage.getItem('ss-user') || 'null'),
  selectedExchange: null,
  notifications: 0,
  assistantOpen: false,
  assistantBusy: false,
  skipProfileFetch: false,
  skipAdminFetch: false,
  recoveryToken: sessionStorage.getItem('ss-recovery-token') || '',
};

const users = [];
const skills = [];
const exchanges = [];
const notifications = [];
const jobs = [];
const ads = [];
const adminCache = {analytics:null, users:[], reports:[], exchanges:[], reviews:[], ads:[], jobs:[], skills:[], categories:[], actions:[], settings:{}};
let messages = [];
let realtimeSocket = null;

function t(ar,en){ return state.lang === 'ar' ? ar : en; }
function esc(value){ return String(value ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); }
function formatDate(value){ try{return new Date(value).toLocaleDateString(state.lang==='ar'?'ar-EG':'en-US',{day:'numeric',month:'short',year:'numeric'});}catch{return value||'';} }
function formatTime(value){ try{return new Date(value).toLocaleTimeString(state.lang==='ar'?'ar-EG':'en-US',{hour:'2-digit',minute:'2-digit'});}catch{return value||'';} }
function initials(name=''){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase() || '?';}
function userBy(id){return users.find(u=>String(u.id)===String(id));}
function exchangeBy(id){return exchanges.find(x=>String(x.id)===String(id));}
function currentUserId(){return state.user?.id || null;}
function routeBase(){return state.route.split('/')[0];}
function isAdmin(){return new Set(['SUPER_ADMIN','ADMIN','MODERATOR','SUPPORT','FINANCE_MANAGER','ADS_MANAGER']).has(state.user?.role);}

function icon(name, size=18){
  const p = {
    home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-5h5v5"/>',
    search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
    user:'<circle cx="12" cy="8" r="3.5"/><path d="M5 20c1.3-3 4-4.5 7-4.5s5.7 1.5 7 4.5"/>',
    users:'<path d="M16 20v-1a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v1"/><circle cx="9.5" cy="7.5" r="3.5"/><path d="M17 4.5a3.3 3.3 0 0 1 0 6.5M21 20v-1a4 4 0 0 0-3-3.85"/>',
    skill:'<path d="m12 3 2.6 5.3L20 9l-4 3.9.95 5.5L12 15.8 7.05 18.4 8 12.9 4 9l5.4-.7L12 3Z"/>',
    exchange:'<path d="M3 7h14l-3-3"/><path d="M21 17H7l3 3"/>',
    chat:'<path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8.2 8.2 0 0 1-4.2-1.1L3 19l1.3-4A7.2 7.2 0 0 1 4.5 11.5 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z"/>',
    bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>',
    briefcase:'<rect x="3" y="6" width="18" height="13" rx="2"/><path d="M8 6V4h8v2M3 11h18M10 11v3h4v-3"/>',
    chart:'<path d="M4 19V5M4 19h17"/><path d="M8 16v-5M12 16V8M16 16v-3M20 16v-7"/>',
    report:'<path d="M12 4 20 19H4L12 4Z"/><path d="M12 9v4M12 16h.01"/>',
    settings:'<path d="M12 2v3M12 19v3M4.93 4.93l2.12 2.12M16.95 16.95l2.12 2.12M2 12h3M19 12h3M4.93 19.07l2.12-2.12M16.95 7.05l2.12-2.12"/><circle cx="12" cy="12" r="3.5"/>',
    shield:'<path d="M12 3 20 6v5c0 5-3.3 8.1-8 10-4.7-1.9-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.3 2.3 4.7-5"/>',
    ad:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 15h5M7 11h8M7 8h10"/>',
    plus:'<path d="M12 5v14M5 12h14"/>',
    arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',
    edit:'<path d="m4 16-.7 4.7L8 20l10.7-10.7a2.2 2.2 0 0 0-3-3L5 17Z"/><path d="m14.5 7.5 3 3"/>',
    trash:'<path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/>',
    check:'<path d="m5 12 4 4L19 6"/>',
    close:'<path d="m6 6 12 12M18 6 6 18"/>',
    menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
    moon:'<path d="M20 15.5A8 8 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5Z"/>',
    sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9 6.3 6.3M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
    logout:'<path d="M10 5H5v14h5M13 8l4 4-4 4M17 12H9"/>',
    filter:'<path d="M4 6h16M7 12h10M10 18h4"/>',
    chevron:'<path d="m8 10 4 4 4-4"/>',
    bot:'<rect x="4" y="7" width="16" height="12" rx="3"/><path d="M9 12h.01M15 12h.01M12 3v4M8 16h8"/>',
    external:'<path d="M14 4h6v6M20 4 12 12"/><path d="M18 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h5"/>',
    star:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z"/>',
  };
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p[name]||p.skill}</svg>`;
}
function avatar(user, cls=''){ const u=user||{name:'?',avatar_url:''}; return `<div class="avatar ${cls}">${u.avatar_url?`<img src="${esc(u.avatar_url)}" alt="">`:esc(initials(u.name))}</div>`; }
function stars(r){const rating=Math.round(Number(r||0));return `<span class="stars" aria-label="${Number(r||0)} / 5">${[0,1,2,3,4].map(i=>i<rating?icon('star',14):'<span class="star-empty">☆</span>').join('')}</span>`;}
function statusTag(s){
  const map={pending:['قيد الانتظار','warning'],accepted:['مقبول','primary'],scheduled:['مجدول','primary'],in_progress:['قيد التنفيذ','primary'],completed:['مكتمل','success'],rejected:['مرفوض','danger'],cancelled:['ملغي','danger'],disputed:['متنازع عليه','danger'],active:['نشط','success'],suspended:['موقوف','warning'],banned:['محظور','danger'],open:['مفتوح','warning'],investigating:['قيد التحقيق','primary'],resolved:['تمت المعالجة','success'],dismissed:['مرفوض','muted'],published:['منشور','success'],hidden:['مخفي','danger'],disabled:['متوقف','muted'],closed:['مغلق','muted']};
  const x=map[s]||[s,'muted']; return `<span class="tag ${x[1]}">${esc(x[0])}</span>`;
}
function toast(msg,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;document.getElementById('toast-root').appendChild(el);setTimeout(()=>el.remove(),2800);}
function showModal(content,size='md'){document.getElementById('modal-root').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal ${size}">${content}</div></div>`;document.body.classList.add('modal-open');}
function closeModal(){document.getElementById('modal-root').innerHTML='';document.body.classList.remove('modal-open');}
function go(route){location.hash=route;}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('ss-theme',state.theme);render();}
function toggleLang(){state.lang=state.lang==='ar'?'en':'ar';localStorage.setItem('ss-lang',state.lang);render();}

const authToken=()=>localStorage.getItem('ss-token')||'';
const refreshToken=()=>localStorage.getItem('ss-refresh')||'';
function saveSession(session,user){if(session?.access_token)localStorage.setItem('ss-token',session.access_token);if(session?.refresh_token)localStorage.setItem('ss-refresh',session.refresh_token);if(user){state.user=user;localStorage.setItem('ss-user',JSON.stringify(user));}}
async function refreshSession(){
  const token=refreshToken(); if(!token) return false;
  const res=await fetch(API_BASE+'/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:token})});
  const data=await res.json().catch(()=>({success:false}));
  if(!res.ok||data.success===false)return false;
  saveSession(data.data.session,data.data.user);
  connectRealtime();
  return true;
}
async function api(path, options={}, retry=true){
  const headers={'Content-Type':'application/json',...(options.headers||{})}; if(authToken())headers.Authorization=`Bearer ${authToken()}`;
  const res=await fetch(API_BASE+path,{...options,headers});
  if(res.status===401 && retry && refreshToken() && !String(path).includes('/auth/refresh')){
    if(await refreshSession()) return api(path,options,false);
  }
  const data=await res.json().catch(()=>({success:false,message:'Invalid server response'}));
  if(!res.ok||data.success===false){const e=new Error(data.message||'Request failed');e.status=res.status;e.code=data.code;throw e;}
  return data.data ?? data;
}

function normalizeUser(u){return {...u,avatar:(u.name||'?').trim().charAt(0)||'?',verified:!!u.is_verified,rating:Number(u.rating||0),exchanges:Number(u.exchanges||0),offers:u.offers||[],needs:u.needs||[]};}
function normalizeSkill(s){return {...s,id:s.id,name:s.name,cat:s.category||'Other',users:Number(s.users||0),requests:Number(s.requests||0)};}
function normalizeExchange(e){return {id:e.id,a:e.sender_id,b:e.receiver_id,offer:e.offered_skill,request:e.requested_skill,type:e.deal_type,status:e.status,created:e.created_at,updated:e.updated_at||e.created_at,message:e.message||''};}
function normalizeMessage(m){return {id:m.id,exchange:m.exchange_id,from:m.sender_id,body:m.body,time:m.sent_at};}
function normalizeJob(j){return {...j,id:j.id};}

async function hydrateBackend(){
  try{
    const [us,sk,adData,jobData]=await Promise.all([api('/users'),api('/skills'),api('/ads'),api('/jobs')]);
    users.splice(0,users.length,...us.map(normalizeUser));
    skills.splice(0,skills.length,...sk.map(normalizeSkill));
    ads.splice(0,ads.length,...adData);
    jobs.splice(0,jobs.length,...jobData.map(normalizeJob));
    if(authToken()){
      try{state.user=await api('/auth/me').then(x=>x.user);localStorage.setItem('ss-user',JSON.stringify(state.user));}
      catch{localStorage.removeItem('ss-token');localStorage.removeItem('ss-user');state.user=null;}
      if(state.user){
        const [ex,ns]=await Promise.all([api('/exchanges'),api('/notifications')]);
        exchanges.splice(0,exchanges.length,...ex.map(normalizeExchange));
        notifications.splice(0,notifications.length,...ns.map(n=>({...n,title:n.title,body:n.body,time:n.created_at,unread:!n.is_read})));
        state.notifications=notifications.filter(n=>n.unread).length;
      }
    }
  }catch(e){
    if(!navigator.onLine)toast(t('أنت غير متصل حاليًا','You are offline'),'error');
    else console.warn(e);
  }
  render();
}

function navItems(admin=false){
  return admin ? [
    ['admin','نظرة عامة','Overview','chart'],['admin/users','المستخدمون','Users','users'],['admin/reports','البلاغات','Reports','report'],['admin/jobs','فرص العمل','Jobs','briefcase'],
    ['admin/exchanges','التبادلات','Exchanges','exchange'],['admin/ads','الإعلانات','Ads','ad'],['admin/reviews','التقييمات','Reviews','star'],['admin/skills','المهارات','Skills','skill'],['admin/categories','التصنيفات','Categories','filter'],
    ['admin/analytics','التحليلات','Analytics','chart'],['admin/actions','سجل الإدارة','Audit log','shield'],['admin/settings','الإعدادات','Settings','settings']
  ] : [
    ['home','الرئيسية','Home','home'],['browse','استكشاف','Discover','search'],['jobs','فرص العمل','Jobs','briefcase'],['exchanges','تبادلاتي','Exchanges','exchange'],['chat','المحادثات','Chat','chat'],['notifications','الإشعارات','Notifications','bell'],['profile','ملفي','Profile','user']
  ];
}
function topbar(admin=false){
  return `<header class="topbar"><div class="topbar-inner">
    <a class="brand" href="#${admin?'admin':'home'}" aria-label="خد وهات"><span class="brand-mark">خ</span><span class="brand-text">خد <span>وهات</span></span></a>
    <div class="global-search"><span class="search-glyph">${icon('search',19)}</span><input id="global-search" aria-label="${t('بحث','Search')}" placeholder="${t('ابحث عن مهارة أو شخص أو وظيفة...','Search skills, people or jobs...')}"></div>
    <div class="top-actions">
      <button class="icon-btn" aria-label="${t('الوضع','Theme')}" onclick="toggleTheme()">${icon(state.theme==='dark'?'sun':'moon')}</button>
      ${!admin?`<a class="icon-btn notification-btn" href="#notifications" aria-label="${t('الإشعارات','Notifications')}">${icon('bell')}<span class="badge-count ${state.notifications?'':'hidden'}">${state.notifications}</span></a>`:''}
      <button class="lang-btn" onclick="toggleLang()">${state.lang==='ar'?'EN':'AR'}</button>
      ${state.user?`<div class="top-user">${avatar(state.user)}<div class="top-user-copy"><strong>${esc(state.user.name)}</strong><span>${admin?'ADMIN':t('عضو','Member')}</span></div></div>`:`<a class="btn btn-primary btn-sm" href="#login">${t('تسجيل الدخول','Sign in')}</a>`}
      ${admin?`<a class="platform-link" href="#home">${icon('external',16)} ${t('المنصة','Platform')}</a>`:''}
    </div>
  </div></header>`;
}
function sidebar(admin=false){
  return `<aside class="sidebar"><div class="sidebar-head"><div class="eyebrow">${admin?'CONTROL CENTER':'WORKSPACE'}</div></div><nav class="sidebar-nav">${navItems(admin).map(([href,ar,en,ic])=>`<a class="nav-item ${state.route===href?'active':''}" href="#${href}">${icon(ic)}<span>${t(ar,en)}</span>${href==='notifications'&&state.notifications?`<b>${state.notifications}</b>`:''}</a>`).join('')}</nav><div class="sidebar-spacer"></div>${state.user?`<button class="nav-item nav-logout" onclick="logout()">${icon('logout')}<span>${t('تسجيل الخروج','Log out')}</span></button>`:''}</aside>`;
}
function mobileNav(){const arr=navItems(false).slice(0,5);return `<nav class="mobile-nav">${arr.map(([href,ar,en,ic])=>`<a class="mobile-item ${state.route===href?'active':''}" href="#${href}">${icon(ic,19)}<span>${t(ar,en)}</span></a>`).join('')}</nav>`;}
function shell(content,admin=false,{assistant=true}={}){return `<div class="app-shell">${topbar(admin)}<div class="workspace">${sidebar(admin)}<main id="app-main" class="main-content">${content}</main></div>${!admin?mobileNav():''}${!admin&&assistant?assistantWidget():''}</div>`;}

function hero(){
  return `<section class="hero-card"><div class="hero-grid"><div><div class="eyebrow light">SKILLS • PEOPLE • OPPORTUNITIES</div><h1>${t('حوّل مهارتك إلى فرصة. وتعلّم من الناس، مش بس من المحتوى.','Turn what you know into opportunity.')}</h1><p>${t('اكتشف أشخاصًا مناسبين لمهاراتك، اعمل تبادل معرفة، تواصل بأمان، واستكشف فرص عمل مرتبطة بما تتقنه.','Find people who complement your skills, exchange knowledge safely, and discover work opportunities that fit your strengths.')}</p><div class="hero-search"><input id="hero-query" placeholder="${t('مثال: UI/UX أو Python أو English','Try: UI/UX, Python or English')}" onkeydown="if(event.key==='Enter')heroSearch()"><button class="btn btn-light" onclick="heroSearch()">${t('ابدأ البحث','Start exploring')} ${icon('arrow',16)}</button></div><div class="hero-trust"><span>${icon('shield',16)} ${t('بلاغات ومراجعة إدارية','Human moderation')}</span><span>${icon('check',16)} ${t('حسابات موثقة','Verified profiles')}</span><span>${icon('chat',16)} ${t('شات بعد قبول التبادل','Private chat')}</span></div></div><div class="hero-orbit"><div class="orbit-ring ring-a"></div><div class="orbit-ring ring-b"></div><div class="orbit-core">${icon('skill',36)}</div><div class="orbit-chip chip-1">${t('UI/UX','UI/UX')}</div><div class="orbit-chip chip-2">${t('Python','Python')}</div><div class="orbit-chip chip-3">${t('Marketing','Marketing')}</div></div></div></section>`;
}
function heroSearch(){const q=document.getElementById('hero-query')?.value.trim()||'';go(`browse${q?`?q=${encodeURIComponent(q)}`:''}`);}
function adBanner(){const ad=ads[0];if(!ad)return '';return `<section class="ad-banner"><div><span class="ad-label">SPONSORED</span><h3>${esc(ad.title)}</h3><p>${esc(ad.description||'')}</p></div><a class="btn btn-dark btn-sm" href="${esc(ad.target_url||'#')}" target="_blank" rel="noreferrer">${t('اعرف أكثر','Learn more')} ${icon('external',14)}</a></section>`;}
function matchCard(u){const offer=u.offers?.[0],need=u.needs?.[0];return `<article class="match-card card"><div class="match-top">${avatar(u,'lg')}<div><div class="user-line"><h3>${esc(u.name)}</h3>${u.verified?`<span class="verified-badge">${icon('check',13)} ${t('موثّق','Verified')}</span>`:''}</div><div class="muted small">${esc(u.location||t('الموقع غير محدد','Location not set'))} · ${u.availability?esc(u.availability):''}</div></div><span class="match-score">${t('مطابقة','Match')} ${Math.min(98,72+(u.rating||0)*5)}%</span></div><div class="match-pair"><div class="pair-box"><span>${t('يقدم','Offers')}</span><strong>${esc(offer?.[0]||t('مهارة متنوعة','Skills'))}</strong><small>${esc(offer?.[1]||'')}</small></div><div class="pair-icon">${icon('exchange',19)}</div><div class="pair-box"><span>${t('يحتاج','Needs')}</span><strong>${esc(need?.[0]||t('مساعدة','Support'))}</strong><small>${esc(need?.[1]||'')}</small></div></div><div class="match-bottom"><div>${stars(u.rating)} <strong>${Number(u.rating||0).toFixed(1)}</strong><span class="muted small"> · ${u.exchanges||0} ${t('تبادل','exchanges')}</span></div><div class="actions"><a class="btn btn-sm" href="#user/${u.id}">${t('الملف','Profile')}</a><button class="btn btn-primary btn-sm" onclick='openRequest("${u.id}")'>${t('طلب تبادل','Request swap')}</button></div></div></article>`;}
function skillCard(s){return `<article class="skill-card card"><div class="skill-icon">${icon('skill',19)}</div><div class="skill-copy"><h3>${esc(s.name)}</h3><p>${esc(s.cat)}</p></div><div class="skill-stats"><span>${s.users} ${t('يعرضونها','offer it')}</span><span>${s.requests} ${t('يطلبونها','need it')}</span></div><button class="card-link" onclick='searchSkill(${JSON.stringify(s.name)})'>${t('استكشف','Explore')} ${icon('arrow',15)}</button></article>`;}
function home(){const rec=users.filter(u=>u.status!=='banned').slice(0,4);return shell(`${hero()}<div class="section-gap">${adBanner()}</div><section class="content-section"><div class="section-head"><div><div class="eyebrow">DISCOVER</div><h2>${t('ناس ممكن تبدأ معاهم تبادل','People worth meeting')}</h2><p>${t('مطابقات مبنية على المهارات والتقييم والتوفر.','Matches based on skills, reputation and availability.')}</p></div><a class="btn btn-sm" href="#browse">${t('استكشف الكل','View all')} ${icon('arrow',15)}</a></div><div class="grid grid-2">${rec.length?rec.map(matchCard).join(''):emptyState(t('جاري تحميل الأشخاص','Loading people...'))}</div></section><section class="content-section"><div class="section-head"><div><div class="eyebrow">SKILLS</div><h2>${t('المهارات الأكثر حركة','Skills getting attention')}</h2><p>${t('اختار مجال وابدأ من أشخاص حقيقيين.','Choose a lane and start with real people.')}</p></div><a class="btn btn-sm" href="#browse">${t('كل المهارات','All skills')}</a></div><div class="grid grid-3">${skills.slice(0,6).map(skillCard).join('')}</div></section><section class="content-section"><div class="section-head"><div><div class="eyebrow">WORK</div><h2>${t('فرص وشغل مرتبطين بمهاراتك','Work that connects to your skills')}</h2></div><a class="btn btn-sm" href="#jobs">${t('كل الفرص','All jobs')}</a></div><div class="grid grid-3">${jobs.slice(0,3).map(jobCard).join('')}</div></section>`,false);}
function emptyState(text){return `<div class="empty-state"><div class="empty-icon">${icon('search',30)}</div><strong>${esc(text)}</strong></div>`;}

function browse(){const query=new URLSearchParams(location.hash.split('?')[1]||'').get('q')||'';return shell(`<div class="page-head"><div><div class="eyebrow">DISCOVER</div><h1>${t('استكشاف المهارات والأشخاص','Discover skills and people')}</h1><p>${t('ابحث، فلتر، ثم اختَر الشخص الأنسب للتبادل.','Search, filter, then choose the right person to exchange with.')}</p></div></div><div class="discover-toolbar card"><div class="search-field"><span>${icon('search',18)}</span><input id="browse-search" value="${esc(query)}" placeholder="${t('اسم مهارة، مجال، مدينة...','Skill, field, city...')}" oninput="filterBrowse()"></div><select id="browse-cat" class="select" onchange="filterBrowse()"><option value="">${t('كل التصنيفات','All categories')}</option>${[...new Set(skills.map(x=>x.cat))].map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="browse-level" class="select" onchange="filterBrowse()"><option value="">${t('كل المستويات','All levels')}</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Expert</option></select></div><div class="browse-tabs"><button class="pill-btn active" data-tab="people" onclick="switchBrowseTab('people')">${icon('users',16)} ${t('أشخاص','People')}</button><button class="pill-btn" data-tab="skills" onclick="switchBrowseTab('skills')">${icon('skill',16)} ${t('مهارات','Skills')}</button></div><section id="browse-results" class="grid grid-2"></section>`,false);}
let browseTab='people';
function switchBrowseTab(tab){browseTab=tab;document.querySelectorAll('.pill-btn').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));filterBrowse();}
function filterBrowse(){const root=document.getElementById('browse-results');if(!root)return;const q=(document.getElementById('browse-search')?.value||'').toLowerCase();const cat=document.getElementById('browse-cat')?.value||'';if(browseTab==='skills'){const data=skills.filter(s=>(!q||s.name.toLowerCase().includes(q)||s.cat.toLowerCase().includes(q))&&(!cat||s.cat===cat));root.innerHTML=data.map(skillCard).join('')||emptyState(t('لا توجد مهارات بالفلتر ده','No skills match this filter'));return;}const level=document.getElementById('browse-level')?.value||'';const data=users.filter(u=>(!q||u.name.toLowerCase().includes(q)||u.location?.toLowerCase().includes(q)||u.offers?.some(x=>String(x[0]).toLowerCase().includes(q)))&&(!level||u.offers?.some(x=>x[1]===level)));root.innerHTML=data.map(matchCard).join('')||emptyState(t('لا توجد نتائج. جرّب كلمة مختلفة.','No results. Try another search.'));}
function searchSkill(name){go(`browse?q=${encodeURIComponent(name)}`);setTimeout(()=>{switchBrowseTab('people');filterBrowse();},80);}

function jobCard(j){const type={remote:'عن بُعد',hybrid:'هجين',on_site:'في الموقع'}[j.job_type]||j.job_type;return `<article class="job-card card"><div class="job-top"><span class="job-type">${esc(type)}</span>${j.owner_verified?`<span class="verified-badge">${icon('check',13)} ${t('ناشر موثّق','Verified')}</span>`:''}</div><h3>${esc(j.title)}</h3><p>${esc(j.description?.slice(0,180)||'')}</p><div class="job-meta"><span>${icon('briefcase',14)} ${esc(j.company||t('جهة مستقلة','Independent'))}</span><span>${esc(j.location||'Remote')}</span></div><div class="tags">${String(j.required_skills||'').split(',').filter(Boolean).slice(0,3).map(s=>`<span class="tag">${esc(s.trim())}</span>`).join('')}</div><div class="card-footer"><span class="muted small">${formatDate(j.created_at)}</span><button class="card-link" onclick='openJob("${j.id}")'>${t('التفاصيل','Details')} ${icon('arrow',15)}</button></div></article>`;}
function jobsPage(){return shell(`<div class="page-head"><div><div class="eyebrow">OPPORTUNITIES</div><h1>${t('فرص العمل','Job opportunities')}</h1><p>${t('وظائف وفرص منشورة من مجتمع المنصة، وتدخل المنشورات الجديدة مراجعة قبل النشر.','Opportunities from the community. New posts are reviewed before publication.')}</p></div><button class="btn btn-primary" onclick="openJobModal()">${icon('plus',17)} ${t('نشر فرصة','Post a job')}</button></div><div class="discover-toolbar card"><div class="search-field"><span>${icon('search',18)}</span><input id="jobs-search" placeholder="${t('ابحث في الوظائف...','Search jobs...')}" oninput="filterJobs()"></div><button class="btn" onclick="loadJobs()">${icon('filter',16)} ${t('تحديث','Refresh')}</button></div><div id="jobs-results" class="grid grid-3">${jobs.map(jobCard).join('')}</div>`,false);}
function filterJobs(){const q=(document.getElementById('jobs-search')?.value||'').toLowerCase();const data=jobs.filter(j=>`${j.title} ${j.description} ${j.company} ${j.required_skills}`.toLowerCase().includes(q));document.getElementById('jobs-results').innerHTML=data.map(jobCard).join('')||emptyState(t('لا توجد وظائف مطابقة','No matching jobs'));}
async function loadJobs(){try{const data=await api('/jobs');jobs.splice(0,jobs.length,...data.map(normalizeJob));filterJobs();toast(t('تم تحديث الوظائف','Jobs refreshed'),'success');}catch(e){toast(e.message,'error');}}

function exchangeCard(e){const other=userBy(String(e.a)===String(currentUserId())?e.b:e.a);return `<article class="exchange-card card"><div class="exchange-head">${avatar(other,'lg')}<div class="exchange-person"><strong>${esc(other?.name||'')}</strong><span>${esc(other?.location||'')}</span></div><div class="exchange-status">${statusTag(e.status)}</div></div><div class="exchange-flow"><div><span>${t('أنت تقدم','You offer')}</span><strong>${esc(e.offer)}</strong></div><div class="flow-arrow">${icon('exchange',20)}</div><div><span>${t('تطلب','You want')}</span><strong>${esc(e.request)}</strong></div></div><div class="exchange-foot"><span class="muted small">${formatDate(e.created)}</span><div class="actions">${e.status==='pending'&&String(e.b)===String(currentUserId())?`<button class="btn btn-primary btn-sm" onclick='changeExchange("${e.id}","accepted")'>${t('قبول','Accept')}</button><button class="btn btn-sm" onclick='changeExchange("${e.id}","rejected")'>${t('رفض','Reject')}</button>`:''}${['accepted','in_progress'].includes(e.status)?`<button class="btn btn-primary btn-sm" onclick='go("exchange/${e.id}")'>${t('فتح التبادل','Open')}</button>`:''}${e.status==='completed'?`<button class="btn btn-sm" onclick='openReview("${e.id}")'>${t('قيّم','Review')}</button>`:''}</div></div></article>`;}
function exchangesPage(){return shell(`<div class="page-head"><div><div class="eyebrow">MY ACTIVITY</div><h1>${t('تبادلاتي','My exchanges')}</h1><p>${t('طلبات، تبادلات جارية، ومراحل الإتمام في مكان واحد.','Requests, active exchanges and completion states in one place.')}</p></div><a class="btn btn-primary" href="#browse">${icon('search',17)} ${t('ابحث عن شخص','Find someone')}</a></div><div class="grid grid-2">${exchanges.map(exchangeCard).join('')||emptyState(t('لا توجد تبادلات بعد','No exchanges yet'))}</div>`,false);}

async function changeExchange(id,status){try{await api(`/exchanges/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});const e=exchangeBy(id);if(e)e.status=status;toast(t('تم تحديث حالة التبادل','Exchange updated'),'success');await hydrateBackend();}catch(e){toast(e.message,'error');}}
async function sendMessage(){const input=document.getElementById('chat-input');const body=input?.value.trim();if(!body)return;try{const m=await api(`/exchanges/${state.selectedExchange}/messages`,{method:'POST',body:JSON.stringify({body})});messages.push(normalizeMessage(m));input.value='';renderChatMessages();}catch(e){toast(e.message,'error');}}
async function selectChat(id){state.selectedExchange=id;try{messages=(await api(`/exchanges/${id}/messages`)).map(normalizeMessage);}catch(e){messages=[];toast(e.message,'error');}go('chat');setTimeout(()=>realtimeSocket?.emit('exchange:join',id),100);}
function chatPage(){const active=exchangeBy(state.selectedExchange)||exchanges.find(e=>['accepted','in_progress'].includes(e.status));if(active)state.selectedExchange=active.id;const other=active?userBy(String(active.a)===String(currentUserId())?active.b:active.a):null;return shell(`<div class="page-head"><div><div class="eyebrow">PRIVATE CHAT</div><h1>${t('المحادثات','Chat')}</h1><p>${t('المحادثة تفتح بعد قبول التبادل فقط، ومرتبطة بالتبادل نفسه.','Chat is available only after an exchange is accepted and stays scoped to that exchange.')}</p></div></div><div class="chat-layout card"><div class="chat-list">${exchanges.filter(e=>['accepted','scheduled','in_progress','completed'].includes(e.status)).map(e=>{const o=userBy(String(e.a)===String(currentUserId())?e.b:e.a);return `<button class="conversation ${String(e.id)===String(state.selectedExchange)?'active':''}" onclick='selectChat("${e.id}")'>${avatar(o)}<span><strong>${esc(o?.name||'')}</strong><small>${esc(e.offer)} ↔ ${esc(e.request)}</small></span></button>`}).join('')||emptyState(t('لا توجد محادثات بعد','No chats yet'))}</div><div class="chat-panel">${active&&other?`<div class="chat-header"><div class="inline">${avatar(other,'lg')}<div><strong>${esc(other.name)}</strong><div class="muted small">${esc(other.availability||'')} · ${statusTag(active.status)}</div></div></div><div class="actions"><button class="btn btn-sm" onclick='go("exchange/${active.id}")'>${t('مساحة التبادل','Exchange workspace')}</button><button class="icon-btn" onclick='openReport("${other.id}")' aria-label="${t('إبلاغ','Report')}">${icon('report',17)}</button></div></div><div id="messages" class="messages"></div><div class="chat-compose"><input id="chat-input" class="input" placeholder="${t('اكتب رسالة محترمة وواضحة...','Write a clear, respectful message...')}" onkeydown="if(event.key==='Enter')sendMessage()"><button class="btn btn-primary" onclick="sendMessage()">${t('إرسال','Send')} ${icon('arrow',15)}</button></div>`:`<div class="empty-state large"><div class="empty-icon">${icon('chat',32)}</div><strong>${t('لا توجد محادثة جاهزة بعد','No active chat yet')}</strong><p>${t('اقبل طلب تبادل أولًا، وبعدها ستظهر المحادثة هنا.','Accept an exchange first, then the conversation will appear here.')}</p><a class="btn btn-primary" href="#exchanges">${t('عرض التبادلات','View exchanges')}</a></div>`}</div></div>`,false,{assistant:false});}
function renderChatMessages(){const root=document.getElementById('messages');if(!root)return;root.innerHTML=messages.map(m=>`<div class="message-row ${String(m.from)===String(currentUserId())?'me':'them'}"><div class="message-bubble">${esc(m.body)}<time>${formatTime(m.time)}</time></div></div>`).join('')||`<div class="empty-state small-state">${t('ابدأ أول رسالة','Send the first message')}</div>`;root.scrollTop=root.scrollHeight;}

function exchangeWorkspace(id){const e=exchangeBy(id),other=e?userBy(String(e.a)===String(currentUserId())?e.b:e.a):null;if(!e)return shell(emptyState(t('التبادل غير موجود','Exchange not found')),false);return shell(`<div class="page-head"><div><div class="eyebrow">EXCHANGE WORKSPACE</div><h1>${esc(e.offer)} ↔ ${esc(e.request)}</h1><p>${esc(other?.name||'')} · ${statusTag(e.status)}</p></div><div class="actions">${['accepted','in_progress'].includes(e.status)?`<button class="btn btn-primary" onclick='go("chat")'>${icon('chat',17)} ${t('فتح الشات','Open chat')}</button>`:''}<button class="btn btn-danger" onclick='changeExchange("${e.id}","cancelled")'>${t('إلغاء','Cancel')}</button></div></div><div class="workspace-grid"><section class="card card-pad"><div class="section-head"><div><div class="eyebrow">DETAILS</div><h2>${t('التفاصيل','Details')}</h2></div>${statusTag(e.status)}</div><div class="grid grid-2"><div class="detail-tile"><span>${t('أنت تقدم','You offer')}</span><strong>${esc(e.offer)}</strong></div><div class="detail-tile"><span>${t('أنت تطلب','You want')}</span><strong>${esc(e.request)}</strong></div></div><div class="notice info"><strong>${t('نصيحة','Tip')}</strong><p>${t('اتفق على نطاق واضح للتبادل ومواعيد مناسبة قبل البداية.','Agree on a clear scope and schedule before you start.')}</p></div><div class="actions">${e.status==='accepted'?`<button class="btn btn-primary" onclick='changeExchange("${e.id}","in_progress")'>${t('بدء التبادل','Start exchange')}</button>`:''}${e.status==='in_progress'?`<button class="btn btn-primary" onclick='changeExchange("${e.id}","completed")'>${t('تسجيل الإتمام','Mark complete')}</button>`:''}</div></section><aside class="card card-pad"><div class="eyebrow">PARTICIPANTS</div><h2>${t('المشاركون','Participants')}</h2><div class="participant">${avatar(state.user,'lg')}<div><strong>${esc(state.user?.name||'')}</strong><span>${t('أنت','You')}</span></div></div><div class="participant">${avatar(other,'lg')}<div><strong>${esc(other?.name||'')}</strong><span>${other?.rating?`${other.rating} ★`:''}</span></div></div><hr><div class="eyebrow">SAFETY</div><p class="muted">${t('يمكنك الإبلاغ عن أي سلوك مخالف من زر البلاغ في الملف أو الشات.','You can report inappropriate behavior from the profile or chat report action.')}</p></aside></div>`,false);}

function notificationsPage(){return shell(`<div class="page-head"><div><div class="eyebrow">UPDATES</div><h1>${t('الإشعارات','Notifications')}</h1><p>${t('كل جديد عن حسابك وتبادلاتك وقرارات الإدارة.','Updates about your account, exchanges and moderation.')}</p></div><button class="btn" onclick="markNotifications()">${t('تحديد الكل كمقروء','Mark all as read')}</button></div><section class="card notification-list">${notifications.map(n=>`<div class="notification-row ${n.unread?'unread':''}"><span class="notification-dot"></span><div><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p><time>${formatDate(n.time)}</time></div></div>`).join('')||emptyState(t('لا توجد إشعارات','No notifications'))}</section>`,false);}
async function markNotifications(){try{await api('/notifications/read-all',{method:'POST'});notifications.forEach(n=>n.unread=false);state.notifications=0;render();}catch(e){toast(e.message,'error');}}

function profile(id=null){const isMe=!id||String(id)===String(currentUserId());const u=isMe?state.user:userBy(id)||{id,name:t('مستخدم','User')};return shell(`<section class="profile-hero card"><div class="profile-gradient"></div><div class="profile-main">${avatar(u,'profile-avatar')}<div class="profile-info"><div><div class="user-line"><h1>${esc(u.name)}</h1>${u.is_verified||u.verified?`<span class="verified-badge">${icon('check',13)} ${t('موثّق','Verified')}</span>`:''}</div><p>${esc(u.bio||t('أضف نبذة تعرف الناس عليك وبما تقدمه.','Add a short bio so people know what you bring.'))}</p><div class="profile-meta"><span>${esc(u.location||t('الموقع غير محدد','Location not set'))}</span><span>${esc(u.language||'العربية')}</span><span>${esc(u.availability||'')}</span></div></div><div class="actions">${isMe?`<button class="btn" onclick="openProfileEdit()">${icon('edit',16)} ${t('تعديل الملف','Edit profile')}</button>`:`<button class="btn" onclick='openReport("${u.id}")'>${icon('report',16)} ${t('إبلاغ','Report')}</button><button class="btn btn-primary" onclick='openRequest("${u.id}")'>${t('طلب تبادل','Request swap')}</button>`}</div></div><div class="profile-stats"><div><strong>${Number(u.rating||0).toFixed(1)}</strong><span>${t('التقييم','Rating')}</span></div><div><strong>${u.exchanges||0}</strong><span>${t('تبادل مكتمل','Completed')}</span></div><div><strong>${(u.offers||[]).length}</strong><span>${t('مهارات مقدمة','Offers')}</span></div></div></div></section><div class="profile-grid"><section class="card card-pad"><div class="section-head"><div><div class="eyebrow">SKILLS</div><h2>${t('المهارات','Skills')}</h2></div>${isMe?`<button class="btn btn-sm" onclick="openAddSkill()">${icon('plus',15)} ${t('إضافة','Add')}</button>`:''}</div><div class="skill-list">${(u.offers||[]).map(x=>`<div class="profile-skill"><span>${icon('skill',15)}</span><div><strong>${esc(x[0])}</strong><small>${esc(x[1]||'')}</small></div><span class="tag primary">${t('أقدمها','Offer')}</span></div>`).join('')}${(u.needs||[]).map(x=>`<div class="profile-skill need"><span>${icon('search',15)}</span><div><strong>${esc(x[0])}</strong><small>${esc(x[1]||'')}</small></div><span class="tag">${t('أريدها','Need')}</span></div>`).join('')||emptyState(t('لا توجد مهارات مضافة','No skills added'))}</div></section><section class="card card-pad"><div class="eyebrow">REPUTATION</div><h2>${t('التقييمات','Reviews')}</h2><div id="profile-reviews" class="reviews-stack">${emptyState(t('اختر مستخدمًا من الاستكشاف لرؤية التقييمات','Open a profile from Discover to view reviews'))}</div></section></div>`,false);}

async function loadProfile(id){try{const data=await api('/users/'+id);const u=normalizeUser(data);const ix=users.findIndex(x=>String(x.id)===String(id));if(ix>=0)users[ix]=u;else users.push(u);state.skipProfileFetch=true;render();const box=document.getElementById('profile-reviews');if(box&&data.reviews?.length)box.innerHTML=data.reviews.map(r=>`<div class="review-card"><div class="review-head"><strong>${esc(r.reviewer_name)}</strong>${stars(r.rating)}</div><p>${esc(r.comment||'')}</p><time>${formatDate(r.created_at)}</time></div>`).join('');}catch(e){toast(e.message,'error');}}

function loginPage(){return `<div class="auth-layout"><section class="auth-visual"><div class="brand large"><span class="brand-mark">خ</span><span class="brand-text">خد <span>وهات</span></span></div><div class="auth-copy"><div class="eyebrow light">SKILL EXCHANGE NETWORK</div><h1>${t('المعرفة أقوى لما تبقى علاقة بين ناس.','Knowledge gets stronger when it becomes a relationship.')}</h1><p>${t('منصة تجمعك بأشخاص مناسبين للتعلّم والتبادل والعمل — مع طبقة أمان وإدارة حقيقية.','A platform to learn, exchange, work and connect — with real moderation and safety controls.')}</p></div><div class="auth-features"><span>${icon('users',18)} ${t('ملفات احترافية','Profiles')}</span><span>${icon('exchange',18)} ${t('تبادلات موثقة','Exchanges')}</span><span>${icon('shield',18)} ${t('إدارة ومراجعة','Moderation')}</span></div></section><section class="auth-panel"><div class="auth-box"><a class="brand" href="#home"><span class="brand-mark">خ</span><span class="brand-text">خد <span>وهات</span></span></a><div class="auth-head"><div class="eyebrow">WELCOME BACK</div><h2>${t('أهلًا برجوعك','Welcome back')}</h2><p>${t('سجّل دخولك وكمّل من حيث توقفت.','Sign in and continue where you left off.')}</p></div><div class="form-stack"><div class="field"><label>Email</label><input id="login-email" class="input" type="email" value="user@khodwehat.local"></div><div class="field"><label>${t('كلمة المرور','Password')}</label><input id="login-pass" class="input" type="password" value="demo123"></div><button class="btn btn-primary btn-block btn-lg" onclick="login()">${t('تسجيل الدخول','Sign in')} ${icon('arrow',16)}</button><button class="btn btn-block" onclick="demoAdminLogin()">${t('الدخول كمدير تجريبي','Demo admin login')}</button><button class="btn btn-ghost btn-block" onclick="go('forgot-password')">${t('نسيت كلمة المرور؟','Forgot password?')}</button><div class="auth-note">${t('تجريبي:','Demo:')} user@khodwehat.local / demo123</div><div class="divider"></div><p class="center muted">${t('لسه ما عندكش حساب؟','New to Khod We Hat?')} <a class="text-link" href="#register">${t('أنشئ حسابًا','Create an account')}</a></p></div></div></section></div>`;}
function registerPage(){return `<div class="auth-layout"><section class="auth-visual"><div class="brand large"><span class="brand-mark">خ</span><span class="brand-text">خد <span>وهات</span></span></div><div class="auth-copy"><div class="eyebrow light">BUILD YOUR SIGNAL</div><h1>${t('اعرض اللي بتتقنه، وخلي الناس تلاقيك بسهولة.','Show what you know. Let the right people find you.')}</h1><p>${t('ملفك المهني هو نقطة البداية للتبادل والشغل والتواصل.','Your profile becomes the starting point for exchange, work and collaboration.')}</p></div></section><section class="auth-panel"><div class="auth-box"><a class="brand" href="#home"><span class="brand-mark">خ</span><span class="brand-text">خد <span>وهات</span></span></a><div class="auth-head"><div class="eyebrow">CREATE ACCOUNT</div><h2>${t('ابدأ حسابك','Create your account')}</h2><p>${t('خلي ملفك واضح، بسيط، وقابل للتواصل.','Keep your profile clear, useful and easy to connect with.')}</p></div><div class="form-stack"><div class="field"><label>${t('الاسم الكامل','Full name')}</label><input id="reg-name" class="input"></div><div class="field"><label>${t('اسم المستخدم','Username')}</label><input id="reg-username" class="input" placeholder="peter.design"></div><div class="field"><label>Email</label><input id="reg-email" class="input" type="email"></div><div class="field"><label>${t('كلمة المرور','Password')}</label><input id="reg-pass" class="input" type="password"></div><div class="grid grid-2"><div class="field"><label>${t('الدولة','Country')}</label><input id="reg-country" class="input" placeholder="Egypt"></div><div class="field"><label>${t('المدينة','City')}</label><input id="reg-city" class="input" placeholder="Cairo"></div></div><div class="field"><label>${t('نبذة قصيرة','Bio')}</label><textarea id="reg-bio" class="textarea" placeholder="${t('عرّف الناس بما تعرفه وما تريد تعلمه','Tell people what you know and want to learn')}"></textarea></div><button class="btn btn-primary btn-block btn-lg" onclick="register()">${t('إنشاء الحساب','Create account')} ${icon('arrow',16)}</button><p class="center muted">${t('عندك حساب؟','Already have an account?')} <a class="text-link" href="#login">${t('تسجيل الدخول','Sign in')}</a></p></div></div></section></div>`;}
function forgotPasswordPage(){return `<div class="auth-layout"><section class="auth-visual"><div class="brand large"><span class="brand-mark">خ</span><span class="brand-text">خد <span>وهات</span></span></div><div class="auth-copy"><div class="eyebrow light">ACCOUNT RECOVERY</div><h1>${t('هنرجعلك حسابك بأمان.','We will help you recover your account securely.')}</h1><p>${t('إعادة كلمة المرور تمر عبر Supabase Auth ولا يتم تخزين أي كلمة مرور في الواجهة.','Password reset is handled through Supabase Auth.')}</p></div></section><section class="auth-panel"><div class="auth-box"><div class="auth-head"><div class="eyebrow">RESET PASSWORD</div><h2>${t('نسيت كلمة المرور؟','Forgot password?')}</h2><p>${t('اكتب بريدك وسنرسل لك رابط إعادة التعيين.','Enter your email and we will send a reset link.')}</p></div><div class="form-stack"><div class="field"><label>Email</label><input id="forgot-email" class="input" type="email"></div><button class="btn btn-primary btn-block btn-lg" onclick="requestPasswordReset()">${t('إرسال رابط التعيين','Send reset link')}</button><button class="btn btn-block" onclick="go('login')">${t('العودة لتسجيل الدخول','Back to sign in')}</button></div></div></section></div>`;}
function resetPasswordPage(){return `<div class="auth-layout"><section class="auth-panel" style="grid-column:1/-1"><div class="auth-box"><div class="auth-head"><div class="eyebrow">SECURE RESET</div><h2>${t('اختَر كلمة مرور جديدة','Choose a new password')}</h2><p>${t('الرابط الذي فتحته سيُستخدم لتأكيد ملكيتك للحساب.','The recovery token from your email is used to authorize this change.')}</p></div><div class="form-stack"><div class="field"><label>${t('كلمة المرور الجديدة','New password')}</label><input id="reset-pass" class="input" type="password"></div><button class="btn btn-primary btn-block btn-lg" onclick="updatePassword()">${t('تحديث كلمة المرور','Update password')}</button></div></div></section></div>`;}
async function login(){try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({email:document.getElementById('login-email').value.trim(),password:document.getElementById('login-pass').value})});saveSession(data.session,data.user);connectRealtime();await hydrateBackend();go(isAdmin()?'admin':'home');toast(t('تم تسجيل الدخول','Signed in'),'success');}catch(e){toast(e.message,'error');}}
async function demoAdminLogin(){document.getElementById('login-email').value='admin@khodwehat.local';document.getElementById('login-pass').value='demo123';await login();}
async function register(){try{const data=await api('/auth/register',{method:'POST',body:JSON.stringify({name:document.getElementById('reg-name').value.trim(),username:document.getElementById('reg-username').value.trim(),email:document.getElementById('reg-email').value.trim(),password:document.getElementById('reg-pass').value,country:document.getElementById('reg-country').value.trim(),city:document.getElementById('reg-city').value.trim(),bio:document.getElementById('reg-bio').value.trim(),location:[document.getElementById('reg-city').value.trim(),document.getElementById('reg-country').value.trim()].filter(Boolean).join(', '),language:'العربية'})});if(data.session){saveSession(data.session,data.user);connectRealtime();await hydrateBackend();go('home');toast(t('تم إنشاء الحساب','Account created'),'success');}else{toast(t('تم إنشاء الحساب. راجع بريدك لتأكيد الحساب ثم سجّل الدخول.','Account created. Check your email to verify it, then sign in.'),'success');go('login');}}catch(e){toast(e.message,'error');}}
async function requestPasswordReset(){try{await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email:document.getElementById('forgot-email').value.trim()})});toast(t('تم إرسال رابط الاستعادة إذا كان البريد مسجلًا.','A reset link was sent if the email is registered.'),'success');go('login');}catch(e){toast(e.message,'error');}}
async function resendVerification(){try{await api('/auth/resend-verification',{method:'POST',body:JSON.stringify({email:document.getElementById('login-email')?.value.trim()})});toast(t('تم طلب بريد التفعيل من جديد.','Verification email requested again.'),'success');}catch(e){toast(e.message,'error');}}
async function updatePassword(){try{const token=state.recoveryToken||sessionStorage.getItem('ss-recovery-token')||'';if(!token)return toast(t('رابط الاستعادة غير صالح أو انتهت صلاحيته.','Recovery link is invalid or expired.'),'error');await api('/auth/update-password',{method:'POST',body:JSON.stringify({access_token:token,password:document.getElementById('reset-pass').value})});sessionStorage.removeItem('ss-recovery-token');state.recoveryToken='';toast(t('تم تحديث كلمة المرور. سجّل الدخول الآن.','Password updated. You can sign in now.'),'success');go('login');}catch(e){toast(e.message,'error');}}
function logout(){realtimeSocket?.disconnect();localStorage.removeItem('ss-token');localStorage.removeItem('ss-refresh');localStorage.removeItem('ss-user');state.user=null;go('login');}

function openRequest(userId){const u=userBy(userId);if(!u)return;showModal(`<div class="modal-head"><div><div class="eyebrow">EXCHANGE REQUEST</div><h2>${t('طلب تبادل','Exchange request')}</h2><span class="muted">${esc(u.name)}</span></div><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="grid grid-2"><div class="field"><label>${t('المهارة التي ستقدمها','What you offer')}</label><select id="req-offer" class="select">${skills.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>${t('المهارة المطلوبة','What you want')}</label><select id="req-need" class="select">${(u.offers||[]).map(x=>{const s=skills.find(s=>s.name===x[0]);return s?`<option value="${s.id}">${esc(s.name)}</option>`:''}).join('')||'<option value="">No offer selected</option>'}</select></div></div><div class="field"><label>${t('نوع الاتفاق','Deal type')}</label><select id="req-type" class="select"><option value="swap">${t('تبادل مهارات','Skill swap')}</option><option value="paid">${t('اتفاق مدفوع','Paid deal')}</option></select></div><div class="field"><label>${t('رسالة افتتاحية','Opening message')}</label><textarea id="req-msg" class="textarea">${esc(`أهلًا ${u.name}، شايف إن مهاراتنا ممكن تكمل بعض. حابب نحدد نطاق التبادل ووقت مناسب للبداية.`)}</textarea></div></div><div class="modal-foot"><button class="btn btn-primary" onclick='submitRequest("${u.id}")'>${t('إرسال الطلب','Send request')} ${icon('arrow',15)}</button><button class="btn" onclick="closeModal()">${t('إلغاء','Cancel')}</button></div>`);}
async function submitRequest(id){try{const payload={receiver_id:id,offered_skill_id:document.getElementById('req-offer').value,requested_skill_id:document.getElementById('req-need').value,deal_type:document.getElementById('req-type').value,message:document.getElementById('req-msg').value};const e=await api('/exchanges',{method:'POST',body:JSON.stringify(payload)});exchanges.unshift(normalizeExchange({...e,offered_skill:skills.find(s=>s.id===payload.offered_skill_id)?.name,requested_skill:skills.find(s=>s.id===payload.requested_skill_id)?.name}));closeModal();toast(t('تم إرسال الطلب','Request sent'),'success');go('exchanges');}catch(e){toast(e.message,'error');}}

function openReport(userId,exchangeId=null){showModal(`<div class="modal-head"><div><div class="eyebrow">SAFETY</div><h2>${t('إرسال بلاغ','Report an issue')}</h2></div><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="field"><label>${t('السبب','Reason')}</label><select id="report-reason" class="select"><option>${t('مضايقة أو إساءة','Harassment')}</option><option>${t('سبام أو محتوى مزعج','Spam')}</option><option>${t('انتحال هوية','Fake profile')}</option><option>${t('احتيال أو محاولة نصب','Scam')}</option><option>${t('مخالفة أخرى','Other policy violation')}</option></select></div><div class="field"><label>${t('التفاصيل','Details')}</label><textarea id="report-desc" class="textarea" placeholder="${t('اكتب ما حدث بالتفصيل...','Describe what happened...')}"></textarea></div><div class="notice warning small">${t('الإدارة تراجع البلاغ وقد تحذر أو توقف أو تحظر الحساب حسب الحالة.','Moderators may warn, suspend or ban accounts based on the review.')}</div></div><div class="modal-foot"><button class="btn btn-danger" onclick='submitReport("${userId}",${exchangeId?`"${exchangeId}"`:'null'})'>${t('إرسال البلاغ','Submit report')}</button><button class="btn" onclick="closeModal()">${t('إلغاء','Cancel')}</button></div>`);}
async function submitReport(userId,exchangeId){try{await api('/reports',{method:'POST',body:JSON.stringify({reported_user_id:userId,exchange_id:exchangeId||undefined,reason:document.getElementById('report-reason').value,description:document.getElementById('report-desc').value})});closeModal();toast(t('تم إرسال البلاغ للإدارة','Report sent to moderation'),'success');}catch(e){toast(e.message,'error');}}

function openProfileEdit(){const u=state.user;showModal(`<div class="modal-head"><h2>${t('تعديل الملف','Edit profile')}</h2><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="field"><label>${t('نبذة','Bio')}</label><textarea id="prof-bio" class="textarea">${esc(u.bio||'')}</textarea></div><div class="grid grid-2"><div class="field"><label>${t('الموقع','Location')}</label><input id="prof-location" class="input" value="${esc(u.location||'')}"></div><div class="field"><label>${t('اللغة','Language')}</label><input id="prof-language" class="input" value="${esc(u.language||'العربية')}"></div></div><div class="grid grid-2"><div class="field"><label>${t('التوفر','Availability')}</label><select id="prof-availability" class="select"><option ${u.availability==='Available now'?'selected':''}>Available now</option><option ${u.availability==='This week'?'selected':''}>This week</option><option>Busy</option></select></div><div class="field"><label>${t('التفضيل','Preferred exchange')}</label><select id="prof-preference" class="select"><option value="swap" ${u.preferred_exchange_type==='swap'?'selected':''}>Skill swap</option><option value="paid" ${u.preferred_exchange_type==='paid'?'selected':''}>Paid deal</option></select></div></div></div><div class="modal-foot"><button class="btn btn-primary" onclick="saveProfile()">${t('حفظ','Save')}</button><button class="btn" onclick="closeModal()">${t('إلغاء','Cancel')}</button></div>`);}
async function saveProfile(){try{const data=await api('/users/me',{method:'PATCH',body:JSON.stringify({bio:document.getElementById('prof-bio').value,location:document.getElementById('prof-location').value,language:document.getElementById('prof-language').value,availability:document.getElementById('prof-availability').value,preferred_exchange_type:document.getElementById('prof-preference').value})});state.user=data;localStorage.setItem('ss-user',JSON.stringify(data));closeModal();render();toast(t('تم تحديث الملف','Profile updated'),'success');}catch(e){toast(e.message,'error');}}
function openAddSkill(){showModal(`<div class="modal-head"><h2>${t('إضافة مهارة','Add skill')}</h2><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="field"><label>${t('المهارة','Skill')}</label><select id="skill-id" class="select">${skills.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="grid grid-2"><div class="field"><label>${t('نوعها في ملفك','Profile role')}</label><select id="skill-type" class="select"><option value="offer">${t('أقدمها','Offer')}</option><option value="need">${t('أريد تعلمها','Need')}</option></select></div><div class="field"><label>${t('المستوى','Level')}</label><select id="skill-level" class="select"><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Expert</option></select></div></div><div class="field"><label>${t('سنوات الخبرة','Years of experience')}</label><input id="skill-years" class="input" type="number" min="0" max="50" value="1"></div><div class="field"><label>${t('ملاحظات','Description')}</label><textarea id="skill-desc" class="textarea"></textarea></div></div><div class="modal-foot"><button class="btn btn-primary" onclick="saveSkill()">${t('إضافة','Add')}</button><button class="btn" onclick="closeModal()">${t('إلغاء','Cancel')}</button></div>`);}
async function saveSkill(){try{await api('/users/me/skills',{method:'POST',body:JSON.stringify({skill_id:document.getElementById('skill-id').value,type:document.getElementById('skill-type').value,level:document.getElementById('skill-level').value,experience_years:Number(document.getElementById('skill-years').value||0),description:document.getElementById('skill-desc').value})});closeModal();await hydrateBackend();toast(t('تمت إضافة المهارة','Skill added'),'success');}catch(e){toast(e.message,'error');}}

function openReview(exchangeId){showModal(`<div class="modal-head"><h2>${t('تقييم التبادل','Review exchange')}</h2><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="field"><label>${t('التقييم','Rating')}</label><select id="review-rating" class="select"><option value="5">5 — ${t('ممتاز','Excellent')}</option><option value="4">4 — ${t('جيد جدًا','Very good')}</option><option value="3">3 — ${t('جيد','Good')}</option><option value="2">2 — ${t('ضعيف','Poor')}</option><option value="1">1 — ${t('سيئ','Bad')}</option></select></div><div class="field"><label>${t('التعليق','Comment')}</label><textarea id="review-comment" class="textarea"></textarea></div></div><div class="modal-foot"><button class="btn btn-primary" onclick='submitReview("${exchangeId}")'>${t('إرسال التقييم','Submit review')}</button><button class="btn" onclick="closeModal()">${t('إلغاء','Cancel')}</button></div>`);}
async function submitReview(id){try{await api(`/exchanges/${id}/reviews`,{method:'POST',body:JSON.stringify({rating:Number(document.getElementById('review-rating').value),comment:document.getElementById('review-comment').value})});closeModal();toast(t('تم إرسال التقييم','Review submitted'),'success');await hydrateBackend();}catch(e){toast(e.message,'error');}}

function openJob(id){const j=jobs.find(x=>String(x.id)===String(id));if(!j)return;showModal(`<div class="modal-head"><div><span class="job-type">${esc(j.job_type)}</span><h2>${esc(j.title)}</h2><span class="muted">${esc(j.company||'')} · ${esc(j.location||'Remote')}</span></div><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body"><p class="prose">${esc(j.description)}</p><div class="tags">${String(j.required_skills||'').split(',').filter(Boolean).map(s=>`<span class="tag">${esc(s.trim())}</span>`).join('')}</div></div><div class="modal-foot"><a class="btn btn-primary" href="#user/${j.owner_id}" onclick="closeModal()">${t('عرض الناشر','View publisher')}</a><button class="btn" onclick="closeModal()">${t('إغلاق','Close')}</button></div>`);}
function openJobModal(existing=null){showModal(`<div class="modal-head"><div><div class="eyebrow">${existing?'EDIT JOB':'POST JOB'}</div><h2>${existing?t('تعديل فرصة','Edit opportunity'):t('نشر فرصة عمل','Post a job')}</h2></div><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="field"><label>${t('العنوان','Title')}</label><input id="job-title" class="input" value="${esc(existing?.title||'')}"></div><div class="field"><label>${t('الوصف','Description')}</label><textarea id="job-description" class="textarea">${esc(existing?.description||'')}</textarea></div><div class="grid grid-2"><div class="field"><label>${t('الجهة','Company')}</label><input id="job-company" class="input" value="${esc(existing?.company||'')}"></div><div class="field"><label>${t('الموقع','Location')}</label><input id="job-location" class="input" value="${esc(existing?.location||'')}"></div></div><div class="grid grid-2"><div class="field"><label>${t('نوع العمل','Type')}</label><select id="job-type" class="select"><option value="remote" ${existing?.job_type==='remote'?'selected':''}>Remote</option><option value="hybrid" ${existing?.job_type==='hybrid'?'selected':''}>Hybrid</option><option value="on_site" ${existing?.job_type==='on_site'?'selected':''}>On-site</option></select></div><div class="field"><label>${t('المهارات المطلوبة','Required skills')}</label><input id="job-skills" class="input" placeholder="Figma, React, Marketing" value="${esc(existing?.required_skills||'')}"></div></div><div class="notice info small">${t('الوظيفة هتروح للمراجعة قبل الظهور العام.','The job goes through moderation before public publishing.')}</div></div><div class="modal-foot"><button class="btn btn-primary" onclick='saveJob(${existing?`"${existing.id}"`:'null'})'>${t('إرسال للمراجعة','Send for review')}</button><button class="btn" onclick="closeModal()">${t('إلغاء','Cancel')}</button></div>`,'lg');}
async function saveJob(id){try{const body={title:document.getElementById('job-title').value,description:document.getElementById('job-description').value,company:document.getElementById('job-company').value,location:document.getElementById('job-location').value,job_type:document.getElementById('job-type').value,required_skills:document.getElementById('job-skills').value};const data=id?await api(`/jobs/${id}`,{method:'PATCH',body:JSON.stringify(body)}):await api('/jobs',{method:'POST',body:JSON.stringify(body)});closeModal();toast(t('تم إرسال الوظيفة للمراجعة','Job sent for review'),'success');await loadJobs();}catch(e){toast(e.message,'error');}}

function assistantWidget(){return `<div class="assistant"><button class="assistant-fab" onclick="toggleAssistant()" aria-label="${t('مساعد خد وهات','خد وهات assistant')}">${icon('bot',23)}<span class="assistant-dot"></span></button><div class="assistant-panel ${state.assistantOpen?'open':''}"><div class="assistant-header"><div class="inline"><div class="assistant-icon">${icon('bot',18)}</div><div><strong>${t('مساعد خد وهات','خد وهات assistant')}</strong><span>${t('يساعدك في الوصول والتواصل','Helps you discover and connect')}</span></div></div><button class="icon-btn" onclick="toggleAssistant()">${icon('close',17)}</button></div><div id="assistant-messages" class="assistant-messages"><div class="assistant-msg bot">${t('أهلًا! اسألني: عايز أتعلم إيه؟ إزاي أتواصل مع شخص؟ أو إزاي أنشر فرصة؟','Hi! Ask me what to learn, how to connect, or how to post an opportunity.')}</div></div><div class="assistant-quick"><button onclick="askAssistant('عايز اتعلم UI/UX')">UI/UX</button><button onclick="askAssistant('ازاي اتواصل مع شخص؟')">${t('التواصل','Connect')}</button><button onclick="askAssistant('ازاي انشر شغل؟')">${t('شغل','Jobs')}</button></div><div class="assistant-compose"><input id="assistant-input" placeholder="${t('اكتب سؤالك...','Type your question...')}" onkeydown="if(event.key==='Enter')askAssistant()"><button onclick="askAssistant()" ${state.assistantBusy?'disabled':''}>${icon('arrow',16)}</button></div></div></div>`;}
function toggleAssistant(){state.assistantOpen=!state.assistantOpen;const panel=document.querySelector('.assistant-panel');if(panel)panel.classList.toggle('open',state.assistantOpen);const input=document.getElementById('assistant-input');if(state.assistantOpen)input?.focus();}
function appendAssistant(text,who='bot'){const root=document.getElementById('assistant-messages');if(!root)return;const d=document.createElement('div');d.className=`assistant-msg ${who}`;d.textContent=text;root.appendChild(d);root.scrollTop=root.scrollHeight;}
async function askAssistant(prefill){const input=document.getElementById('assistant-input');const msg=((prefill ?? input?.value) || '').trim();if(!msg||state.assistantBusy)return;state.assistantBusy=true;appendAssistant(msg,'user');if(input)input.value='';try{const out=await api('/assistant',{method:'POST',body:JSON.stringify({message:msg,current_page:state.route})});appendAssistant(out.reply,'bot');(out.suggestions||[]).slice(0,3).forEach(s=>{const root=document.getElementById('assistant-messages');if(!root)return;const a=document.createElement('button');a.className='assistant-suggestion';a.textContent=s.label;a.onclick=()=>{if(s.query)go(`browse?q=${encodeURIComponent(s.query)}`);else go(s.route);};root.appendChild(a);});}catch(e){appendAssistant(t('حصلت مشكلة، جرّب فتح الاستكشاف مباشرة.','Something went wrong. Try opening Discover directly.'),'bot');}finally{state.assistantBusy=false;}}

// ============================= ADMIN =============================
function adminDashboard(){const a=adminCache.analytics||{};const cards=[['إجمالي المستخدمين','Total users',a.total_users||0,'users'],['المستخدمون النشطون','Active',a.active_users||0,'check'],['تبادلات مكتملة','Completed',a.completed_exchanges||0,'exchange'],['بلاغات مفتوحة','Open reports',a.open_reports||0,'report'],['وظائف منشورة','Published jobs',a.published_jobs||0,'briefcase'],['إعلانات نشطة','Active ads',a.active_ads||0,'ad']];return shell(`<div class="page-head"><div><div class="eyebrow">CONTROL CENTER</div><h1>${t('لوحة الإدارة','Admin control center')}</h1><p>${t('كل قرار إداري هنا بيوصل للـbackend ويتسجل في السجل.','Every moderation decision here is server-authoritative and audited.')}</p></div><span class="admin-pill">${icon('shield',15)} ADMIN</span></div><div class="grid grid-3">${cards.map(c=>`<div class="stat-card card"><div class="stat-icon">${icon(c[3],19)}</div><span>${t(c[0],c[1])}</span><strong>${Number(c[2]).toLocaleString()}</strong><small>${c[1]}</small></div>`).join('')}</div><div class="section-gap grid grid-2"><div class="card card-pad"><div class="section-head"><div><div class="eyebrow">MODERATION</div><h2>${t('آخر البلاغات','Recent reports')}</h2></div><a class="btn btn-sm" href="#admin/reports">${t('فتح البلاغات','Open reports')}</a></div>${adminCache.reports.slice(0,4).map(reportRowMini).join('')||emptyState(t('لا توجد بلاغات','No reports'))}</div><div class="card card-pad"><div class="section-head"><div><div class="eyebrow">HEALTH</div><h2>${t('صحة المنصة','Platform health')}</h2></div></div>${healthBars(a)}</div></div>`,true,{assistant:false});}
function healthBars(a){const rows=[['Active users',Number(a.active_users||0),Math.max(1,Number(a.total_users||1))],['Completed exchanges',Number(a.completed_exchanges||0),Math.max(1,Number(a.total_exchanges||1))],['Published jobs',Number(a.published_jobs||0),Math.max(1,Number(a.published_jobs||1))]];return rows.map(r=>`<div class="health-row"><div class="space"><span>${r[0]}</span><strong>${Math.min(100,Math.round(r[1]/r[2]*100))}%</strong></div><div class="progress"><span style="width:${Math.min(100,Math.round(r[1]/r[2]*100))}%"></span></div></div>`).join('');}
function reportRowMini(r){return `<div class="report-mini"><span class="notification-dot"></span><div><strong>${esc(r.reported_name)}</strong><small>${esc(r.reason)} · ${formatDate(r.created_at)}</small></div>${statusTag(r.status)}<button class="btn btn-sm" onclick='openAdminReport("${r.id}")'>${t('مراجعة','Review')}</button></div>`;}
function adminTablePage(type){const builders={
 'admin/users':adminUsersPage,'admin/reports':adminReportsPage,'admin/jobs':adminJobsPage,'admin/exchanges':adminExchangesPage,'admin/ads':adminAdsPage,'admin/reviews':adminReviewsPage,'admin/skills':adminSkillsPage,'admin/categories':adminCategoriesPage,'admin/actions':adminActionsPage};const fn=builders[type]||adminUsersPage;return shell(fn(),true,{assistant:false});}
function tableWrap(content){return `<div class="table-wrap card">${content}</div>`;}
function adminUsersPage(){return `<div class="page-head"><div><div class="eyebrow">USERS</div><h1>${t('المستخدمون','Users')}</h1><p>${t('مشاهدة وإدارة كل الحسابات وحالاتها.','View and manage all accounts and their status.')}</p></div></div><div class="admin-filters"><input id="admin-user-search" class="input" placeholder="${t('ابحث بالاسم أو البريد...','Search by name or email...')}" oninput="filterAdminUsers()"><select id="admin-user-status" class="select" onchange="filterAdminUsers()"><option value="">${t('كل الحالات','All statuses')}</option><option>active</option><option>suspended</option><option>banned</option></select></div><div id="admin-users-table"></div>`;}
function renderAdminUsers(list=adminCache.users){document.getElementById('admin-users-table').innerHTML=tableWrap(`<table class="table"><thead><tr><th>${t('المستخدم','User')}</th><th>${t('الحالة','Status')}</th><th>${t('التوثيق','Verification')}</th><th>${t('التقييم','Rating')}</th><th>${t('التبادلات','Exchanges')}</th><th>${t('إجراء','Action')}</th></tr></thead><tbody>${list.map(u=>`<tr><td><div class="inline">${avatar(u)}<div><strong>${esc(u.name)}</strong><small>${esc(u.email)}</small></div></div></td><td>${statusTag(u.status)}</td><td>${u.is_verified?`<span class="verified-badge">${icon('check',13)} Verified</span>`:`<span class="muted small">Not verified</span>`}</td><td>${stars(u.rating)} ${Number(u.rating||0).toFixed(1)}</td><td>${u.exchanges||0}</td><td><div class="actions"><button class="btn btn-sm" onclick='openAdminUser("${u.id}")'>${t('إدارة','Manage')}</button></div></td></tr>`).join('')}</tbody></table>`);}
function filterAdminUsers(){const q=(document.getElementById('admin-user-search')?.value||'').toLowerCase();const s=document.getElementById('admin-user-status')?.value||'';renderAdminUsers(adminCache.users.filter(u=>(!q||`${u.name} ${u.email} ${u.location}`.toLowerCase().includes(q))&&(!s||u.status===s)));}
function openAdminUser(id){const u=adminCache.users.find(x=>String(x.id)===String(id));if(!u)return;showModal(`<div class="modal-head"><div class="inline">${avatar(u,'lg')}<div><h2>${esc(u.name)}</h2><span class="muted">${esc(u.email)}</span></div></div><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="user-detail-grid"><div><span>${t('الحالة','Status')}</span><strong>${statusTag(u.status)}</strong></div><div><span>${t('التوثيق','Verification')}</span><strong>${u.is_verified?t('موثّق','Verified'):t('غير موثّق','Not verified')}</strong></div><div><span>${t('التقييم','Rating')}</span><strong>${Number(u.rating||0).toFixed(1)}</strong></div><div><span>${t('التبادلات','Exchanges')}</span><strong>${u.exchanges||0}</strong></div></div><div class="grid grid-2"><div class="field"><label>${t('الدور','Role')}</label><select id="admin-role-select" class="select">${['USER','SUPER_ADMIN','ADMIN','MODERATOR','SUPPORT','FINANCE_MANAGER','ADS_MANAGER'].map(role=>`<option ${u.role===role?'selected':''}>${role}</option>`).join('')}</select></div><div class="field"><label>${t('إجراءات الحساب','Account actions')}</label><button class="btn" onclick='adminResetPassword("${u.id}")'>${t('إنشاء رابط إعادة كلمة المرور','Generate reset link')}</button></div></div><div class="notice info"><strong>${t('ملاحظة إدارة','Admin note')}</strong><p>${t('كل تغيير حساس يتسجل في Audit Log. تغيير الحالة يؤثر فورًا على تسجيل الدخول.','Sensitive changes are audited. Status changes affect authentication immediately.')}</p></div></div><div class="modal-foot"><button class="btn btn-primary" onclick='adminUserAction("${u.id}","active")'>${t('تفعيل','Activate')}</button><button class="btn btn-danger" onclick='adminUserAction("${u.id}","suspended")'>${t('إيقاف','Suspend')}</button><button class="btn btn-danger" onclick='adminUserAction("${u.id}","banned")'>${t('حظر','Ban')}</button><button class="btn" onclick='adminVerify("${u.id}",${!u.is_verified})'>${u.is_verified?t('إزالة التوثيق','Unverify'):t('توثيق','Verify')}</button><button class="btn btn-danger" onclick='adminDeleteUser("${u.id}")'>${t('حذف الحساب','Delete account')}</button><button class="btn btn-primary" onclick='adminChangeRole("${u.id}")'>${t('حفظ الدور','Save role')}</button></div>`,'lg');}
async function adminUserAction(id,status){try{await api(`/admin/users/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});closeModal();toast(t('تم تنفيذ الإجراء','Action completed'),'success');await loadAdmin('users');}catch(e){toast(e.message,'error');}}
async function adminVerify(id,val){try{await api(`/admin/users/${id}/verification`,{method:'PATCH',body:JSON.stringify({is_verified:val})});closeModal();toast(t('تم تحديث التوثيق','Verification updated'),'success');await loadAdmin('users');}catch(e){toast(e.message,'error');}}
async function adminChangeRole(id){try{const role=document.getElementById('admin-role-select').value;await api(`/admin/users/${id}/role`,{method:'PATCH',body:JSON.stringify({role})});closeModal();toast(t('تم تحديث الدور','Role updated'),'success');await loadAdmin('users');}catch(e){toast(e.message,'error');}}
async function adminResetPassword(id){try{const out=await api(`/admin/users/${id}/password-reset`,{method:'POST'});if(out.action_link){navigator.clipboard?.writeText(out.action_link);showModal(`<div class="modal-head"><h2>${t('رابط إعادة كلمة المرور','Password reset link')}</h2><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body"><p class="muted">${t('تم إنشاء الرابط. تم نسخه للحافظة إن كان المتصفح يسمح بذلك.','A recovery link was generated and copied when the browser allowed it.')}</p><div class="notice"><code style="word-break:break-all">${esc(out.action_link)}</code></div></div>`,'lg');}else toast(t('تم إنشاء إجراء الاستعادة','Recovery action created'),'success');}catch(e){toast(e.message,'error');}}
async function adminDeleteUser(id){if(!confirm(t('حذف الحساب نهائيًا؟ سيتم حذف بيانات الملف المرتبطة به.','Delete this account permanently? Related profile data will be removed.')))return;try{await api(`/admin/users/${id}`,{method:'DELETE'});closeModal();toast(t('تم حذف الحساب','Account deleted'),'success');await loadAdmin('users');await hydrateBackend();}catch(e){toast(e.message,'error');}}
function adminReportsPage(){return `<div class="page-head"><div><div class="eyebrow">MODERATION</div><h1>${t('البلاغات','Reports')}</h1><p>${t('راجع البلاغات واتخذ قرارًا إداريًا واضحًا مع تسجيل السبب.','Review reports and make an explicit, audited moderation decision.')}</p></div></div>${tableWrap(`<table class="table"><thead><tr><th>${t('المبلّغ','Reporter')}</th><th>${t('الحساب المبلغ عنه','Reported user')}</th><th>${t('السبب','Reason')}</th><th>${t('الحالة','Status')}</th><th>${t('التاريخ','Date')}</th><th></th></tr></thead><tbody>${adminCache.reports.map(r=>`<tr><td>${esc(r.reporter_name)}</td><td><strong>${esc(r.reported_name)}</strong><small>${esc(r.reported_email||'')}</small></td><td>${esc(r.reason)}</td><td>${statusTag(r.status)}</td><td>${formatDate(r.created_at)}</td><td><button class="btn btn-sm" onclick='openAdminReport("${r.id}")'>${t('مراجعة','Review')}</button></td></tr>`).join('')}</tbody></table>`)}`;}
function openAdminReport(id){const r=adminCache.reports.find(x=>String(x.id)===String(id));if(!r)return;showModal(`<div class="modal-head"><div><div class="eyebrow">REPORT REVIEW</div><h2>${esc(r.reason)}</h2><span class="muted">${esc(r.reporter_name)} → ${esc(r.reported_name)}</span></div><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="notice"><strong>${t('الوصف','Description')}</strong><p>${esc(r.description||t('لا يوجد وصف','No description provided'))}</p></div><div class="field"><label>${t('ملاحظة الإدارة','Moderator note')}</label><textarea id="mod-note" class="textarea"></textarea></div><div class="mod-actions"><button class="btn" onclick='moderateReport("${r.id}","investigate")'>${t('تحقيق','Investigate')}</button><button class="btn" onclick='moderateReport("${r.id}","warn")'>${t('تحذير','Warn')}</button><button class="btn btn-danger" onclick='moderateReport("${r.id}","suspend")'>${t('إيقاف الحساب','Suspend account')}</button><button class="btn btn-danger" onclick='moderateReport("${r.id}","ban")'>${t('حظر الحساب','Ban account')}</button><button class="btn" onclick='moderateReport("${r.id}","dismiss")'>${t('رفض البلاغ','Dismiss')}</button></div></div>`,'lg');}
async function moderateReport(id,action){try{await api(`/admin/reports/${id}`,{method:'PATCH',body:JSON.stringify({action,note:document.getElementById('mod-note')?.value||''})});closeModal();toast(t('تمت معالجة البلاغ','Report moderated'),'success');await loadAdmin('reports');}catch(e){toast(e.message,'error');}}
function adminJobsPage(){return `<div class="page-head"><div><div class="eyebrow">OPPORTUNITIES</div><h1>${t('فرص العمل','Jobs')}</h1><p>${t('المحتوى الوظيفي يمر بمراجعة قبل النشر.','Job content is reviewed before publication.')}</p></div></div>${tableWrap(`<table class="table"><thead><tr><th>${t('العنوان','Title')}</th><th>${t('الناشر','Owner')}</th><th>${t('النوع','Type')}</th><th>${t('الحالة','Status')}</th><th>${t('التاريخ','Date')}</th><th></th></tr></thead><tbody>${adminCache.jobs.map(j=>`<tr><td><strong>${esc(j.title)}</strong><small>${esc(j.company||'')}</small></td><td>${esc(j.owner_name)}</td><td>${esc(j.job_type)}</td><td>${statusTag(j.status)}</td><td>${formatDate(j.created_at)}</td><td><div class="actions"><button class="btn btn-sm btn-primary" onclick='moderateJob("${j.id}","published")'>${t('نشر','Publish')}</button><button class="btn btn-sm" onclick='moderateJob("${j.id}","rejected")'>${t('رفض','Reject')}</button><button class="btn btn-sm btn-danger" onclick='moderateJob("${j.id}","suspended")'>${t('إيقاف','Suspend')}</button></div></td></tr>`).join('')}</tbody></table>`)}`;}
async function moderateJob(id,status){try{await api(`/admin/jobs/${id}/moderation`,{method:'PATCH',body:JSON.stringify({status})});toast(t('تم تحديث الوظيفة','Job updated'),'success');await loadAdmin('jobs');}catch(e){toast(e.message,'error');}}
function adminExchangesPage(){return `<div class="page-head"><div><div class="eyebrow">EXCHANGES</div><h1>${t('التبادلات','Exchanges')}</h1><p>${t('للمراجعة الإدارية والتدخل في الحالات المتنازع عليها.','Administrative review and intervention for disputes.')}</p></div></div>${tableWrap(`<table class="table"><thead><tr><th>ID</th><th>${t('الأطراف','Participants')}</th><th>${t('المهارات','Skills')}</th><th>${t('الحالة','Status')}</th><th></th></tr></thead><tbody>${adminCache.exchanges.map(e=>`<tr><td><code>#${String(e.id).slice(0,8)}</code></td><td>${esc(e.sender_name)} ↔ ${esc(e.receiver_name)}</td><td>${esc(e.offered_skill)} ↔ ${esc(e.requested_skill)}</td><td>${statusTag(e.status)}</td><td><select class="table-select" onchange='adminExchangeStatus("${e.id}",this.value)'><option value="">${t('تغيير...','Change...')}</option>${['pending','accepted','scheduled','rejected','in_progress','completed','disputed','cancelled'].map(s=>`<option value="${s}">${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table>`)}`;}
async function adminExchangeStatus(id,status){if(!status)return;try{await api(`/admin/exchanges/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});toast(t('تم تحديث التبادل','Exchange updated'),'success');await loadAdmin('exchanges');}catch(e){toast(e.message,'error');}}
function adminAdsPage(){return `<div class="page-head"><div><div class="eyebrow">MONETIZATION</div><h1>${t('الإعلانات','Advertisements')}</h1><p>${t('إنشاء ونشر وتعطيل الإعلانات من لوحة الإدارة.','Create, publish and disable ads from one place.')}</p></div><button class="btn btn-primary" onclick="openAdModal()">${icon('plus',16)} ${t('إعلان جديد','New ad')}</button></div><div class="grid grid-2">${adminCache.ads.map(ad=>`<article class="card card-pad"><div class="space"><div><span class="ad-label">${esc(ad.placement)}</span><h3>${esc(ad.title)}</h3></div>${statusTag(ad.status)}</div><p class="muted">${esc(ad.description||'')}</p><div class="actions"><button class="btn btn-sm" onclick='openAdModal(${JSON.stringify(ad).replace(/'/g,'&#039;')})'>${icon('edit',15)} ${t('تعديل','Edit')}</button><button class="btn btn-sm btn-danger" onclick='deleteAd("${ad.id}")'>${icon('trash',15)} ${t('حذف','Delete')}</button></div></article>`).join('')||emptyState(t('لا توجد إعلانات','No advertisements'))}</div>`;}
function openAdModal(ad=null){showModal(`<div class="modal-head"><div><div class="eyebrow">ADS</div><h2>${ad?t('تعديل إعلان','Edit advertisement'):t('إعلان جديد','New advertisement')}</h2></div><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="field"><label>${t('العنوان','Title')}</label><input id="ad-title" class="input" value="${esc(ad?.title||'')}"></div><div class="field"><label>${t('الوصف','Description')}</label><textarea id="ad-description" class="textarea">${esc(ad?.description||'')}</textarea></div><div class="grid grid-2"><div class="field"><label>${t('المعلن','Advertiser')}</label><input id="ad-advertiser" class="input" value="${esc(ad?.advertiser_name||'خد وهات')}" ></div><div class="field"><label>${t('المكان','Placement')}</label><select id="ad-placement" class="select">${['HOME_HERO','HOME_FEED','BROWSE_TOP','PROFILE_BOTTOM'].map(x=>`<option ${ad?.placement===x?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="grid grid-2"><div class="field"><label>${t('الرابط','Destination URL')}</label><input id="ad-url" class="input" value="${esc(ad?.target_url||'')}" placeholder="https://"></div><div class="field"><label>${t('رابط الصورة','Image URL')}</label><input id="ad-image" class="input" value="${esc(ad?.image_url||'')}" placeholder="https://..."></div></div><div class="grid grid-2"><div class="field"><label>${t('الحالة','Status')}</label><select id="ad-status" class="select"><option ${ad?.status==='active'?'selected':''}>active</option><option ${ad?.status==='disabled'?'selected':''}>disabled</option></select></div><div class="field"><label>${t('الأولوية','Priority')}</label><input id="ad-priority" class="input" type="number" value="${Number(ad?.priority||0)}"></div></div></div><div class="modal-foot"><button class="btn btn-primary" onclick='saveAd(${ad?`"${ad.id}"`:'null'})'>${t('حفظ','Save')}</button><button class="btn" onclick="closeModal()">${t('إلغاء','Cancel')}</button></div>`,'lg');}
async function saveAd(id){try{const body={title:document.getElementById('ad-title').value,description:document.getElementById('ad-description').value,advertiser_name:document.getElementById('ad-advertiser').value,placement:document.getElementById('ad-placement').value,target_url:document.getElementById('ad-url').value,image_url:document.getElementById('ad-image').value,status:document.getElementById('ad-status').value,priority:Number(document.getElementById('ad-priority').value||0)};await api(id?`/admin/ads/${id}`:'/admin/ads',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();toast(t('تم حفظ الإعلان','Advertisement saved'),'success');await loadAdmin('ads');}catch(e){toast(e.message,'error');}}
async function deleteAd(id){if(!confirm(t('حذف الإعلان نهائيًا؟','Delete this advertisement permanently?')))return;try{await api(`/admin/ads/${id}`,{method:'DELETE'});toast(t('تم حذف الإعلان','Advertisement deleted'),'success');await loadAdmin('ads');}catch(e){toast(e.message,'error');}}
function adminReviewsPage(){return `<div class="page-head"><div><div class="eyebrow">REPUTATION</div><h1>${t('التقييمات','Reviews')}</h1><p>${t('إخفاء التقييمات المخالفة بدون حذف التاريخ الإداري.','Hide inappropriate reviews without losing auditability.')}</p></div></div>${tableWrap(`<table class="table"><thead><tr><th>${t('الكاتب','Reviewer')}</th><th>${t('للـمستخدم','Reviewee')}</th><th>${t('التقييم','Rating')}</th><th>${t('الحالة','Status')}</th><th></th></tr></thead><tbody>${adminCache.reviews.map(r=>`<tr><td>${esc(r.reviewer_name)}</td><td>${esc(r.reviewee_name)}</td><td>${stars(r.rating)} ${r.rating}</td><td>${statusTag(r.status)}</td><td><button class="btn btn-sm" onclick='moderateReview("${r.id}","${r.status==='active'?'hidden':'active'}")'>${r.status==='active'?t('إخفاء','Hide'):t('إظهار','Show')}</button></td></tr>`).join('')}</tbody></table>`)}`;}
async function moderateReview(id,status){try{await api(`/admin/reviews/${id}`,{method:'PATCH',body:JSON.stringify({status})});toast(t('تم تحديث التقييم','Review updated'),'success');await loadAdmin('reviews');}catch(e){toast(e.message,'error');}}
function adminSkillsPage(){return `<div class="page-head"><div><div class="eyebrow">TAXONOMY</div><h1>${t('المهارات','Skills')}</h1><p>${t('إدارة المهارات التي تعتمد عليها المطابقة والبحث.','Manage skills used by discovery and matching.')}</p></div><button class="btn btn-primary" onclick="openTaxonomyModal('skill')">${icon('plus',16)} ${t('إضافة مهارة','Add skill')}</button></div>${tableWrap(`<table class="table"><thead><tr><th>${t('المهارة','Skill')}</th><th>${t('التصنيف','Category')}</th><th>${t('المستخدمون','Users')}</th><th></th></tr></thead><tbody>${adminCache.skills.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.category||'')}</td><td>${s.id?skills.find(x=>x.name===s.name)?.users??0:0}</td><td><div class="actions"><button class="btn btn-sm" onclick='openTaxonomyModal("skill",${JSON.stringify(s).replace(/'/g,'&#039;')})'>${t('تعديل','Edit')}</button><button class="btn btn-sm btn-danger" onclick='deleteTaxonomy("skill","${s.id}")'>${t('حذف','Delete')}</button></div></td></tr>`).join('')}</tbody></table>`)}`;}
function adminCategoriesPage(){return `<div class="page-head"><div><div class="eyebrow">TAXONOMY</div><h1>${t('التصنيفات','Categories')}</h1></div><button class="btn btn-primary" onclick="openTaxonomyModal('category')">${icon('plus',16)} ${t('تصنيف جديد','New category')}</button></div><div class="grid grid-3">${adminCache.categories.map(c=>`<article class="card card-pad"><div class="space"><strong>${esc(c.name)}</strong><span class="tag">${c.skill_count} skills</span></div><div class="actions" style="margin-top:16px"><button class="btn btn-sm" onclick='openTaxonomyModal("category",${JSON.stringify(c).replace(/'/g,'&#039;')})'>${t('تعديل','Edit')}</button><button class="btn btn-sm btn-danger" onclick='deleteTaxonomy("category","${c.id}")'>${t('حذف','Delete')}</button></div></article>`).join('')}</div>`;}
function openTaxonomyModal(type,data=null){const cats=adminCache.categories;showModal(`<div class="modal-head"><h2>${data?t('تعديل','Edit'):t('إضافة','Add')} ${type==='skill'?t('مهارة','skill'):t('تصنيف','category')}</h2><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body form-stack"><div class="field"><label>${t('الاسم','Name')}</label><input id="tax-name" class="input" value="${esc(data?.name||'')}"></div>${type==='skill'?`<div class="field"><label>${t('التصنيف','Category')}</label><select id="tax-cat" class="select"><option value="">${t('بدون','None')}</option>${cats.map(c=>`<option value="${c.id}" ${String(data?.category_id||'')===String(c.id)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div>`:''}</div><div class="modal-foot"><button class="btn btn-primary" onclick='saveTaxonomy("${type}",${data?`"${data.id}"`:'null'})'>${t('حفظ','Save')}</button><button class="btn" onclick="closeModal()">${t('إلغاء','Cancel')}</button></div>`);}
async function saveTaxonomy(type,id){try{if(type==='skill'){const body={name:document.getElementById('tax-name').value,category_id:document.getElementById('tax-cat').value||null};await api(id?`/admin/skills/${id}`:'/admin/skills',{method:id?'PATCH':'POST',body:JSON.stringify(body)});}else{const body={name:document.getElementById('tax-name').value};await api(id?`/admin/categories/${id}`:'/admin/categories',{method:id?'PATCH':'POST',body:JSON.stringify(body)});}closeModal();toast(t('تم الحفظ','Saved'),'success');await loadAdmin(type==='skill'?'skills':'categories');await hydrateBackend();}catch(e){toast(e.message,'error');}}
async function deleteTaxonomy(type,id){if(!confirm(t('حذف هذا العنصر؟ قد يؤثر على المهارات المرتبطة.','Delete this item? Linked skills may be affected.')))return;try{await api(`/admin/${type==='skill'?'skills':'categories'}/${id}`,{method:'DELETE'});await loadAdmin(type==='skill'?'skills':'categories');await hydrateBackend();toast(t('تم الحذف','Deleted'),'success');}catch(e){toast(e.message,'error');}}
function adminAnalytics(){const a=adminCache.analytics||{};return `<div class="page-head"><div><div class="eyebrow">ANALYTICS</div><h1>${t('التحليلات','Analytics')}</h1><p>${t('مؤشرات تشغيلية فعلية من قاعدة البيانات.','Operational indicators from the live database.')}</p></div></div><div class="grid grid-4">${[['Users',a.total_users],['Active',a.active_users],['Suspended',a.suspended_users],['Banned',a.banned_users],['Exchanges',a.total_exchanges],['Completed',a.completed_exchanges],['Open reports',a.open_reports],['Average rating',a.average_rating]].map(x=>`<div class="stat-card card"><span>${x[0]}</span><strong>${Number(x[1]||0).toLocaleString()}</strong></div>`).join('')}</div><section class="section-gap grid grid-2"><div class="card card-pad"><div class="eyebrow">GROWTH</div><h2>${t('نمو المستخدمين','User growth')}</h2><div class="chart">${(a.user_growth||[]).map(x=>{const max=Math.max(...(a.user_growth||[]).map(y=>y.users),1);return `<div class="bar" style="height:${Math.max(8,x.users/max*100)}%"><span>${esc(x.month.slice(5))}</span></div>`}).join('')}</div></div><div class="card card-pad"><div class="eyebrow">CONVERSION</div><h2>${t('صحة التبادل','Exchange health')}</h2>${healthBars(a)}</div></section>`;}
function adminActionsPage(){return `<div class="page-head"><div><div class="eyebrow">AUDIT</div><h1>${t('سجل الإدارة','Admin audit log')}</h1><p>${t('كل قرار حساس قابل للمراجعة من الإدارة.','Sensitive admin actions stay auditable.')}</p></div></div>${tableWrap(`<table class="table"><thead><tr><th>${t('المدير','Admin')}</th><th>${t('الإجراء','Action')}</th><th>${t('الهدف','Target')}</th><th>${t('الملاحظة','Note')}</th><th>${t('التاريخ','Date')}</th></tr></thead><tbody>${adminCache.actions.map(a=>`<tr><td>${esc(a.admin_name)}</td><td>${esc(a.action)}</td><td>${esc(a.target_user_name||'—')}</td><td>${esc(a.note)}</td><td>${formatDate(a.created_at)}</td></tr>`).join('')}</tbody></table>`)}`;}
function adminSettingsPage(){const s=adminCache.settings||{};return `<div class="page-head"><div><div class="eyebrow">PLATFORM</div><h1>${t('الإعدادات','Settings')}</h1><p>${t('تحكم في سلوكيات حساسة من الـbackend، وليس من الواجهة فقط.','Control sensitive behavior server-side, not just in the UI.')}</p></div><button class="btn btn-primary" onclick="saveAdminSettings()">${t('حفظ الإعدادات','Save settings')}</button></div><div class="grid grid-2"><section class="card card-pad form-stack"><label class="setting-row"><span><strong>${t('السماح بالتسجيل','Registration')}</strong><small>${t('حظر التسجيلات الجديدة','Allow new accounts')}</small></span><input id="set-registration" type="checkbox" ${s.registration_enabled?'checked':''}></label><label class="setting-row"><span><strong>${t('الإعلانات','Advertising')}</strong><small>${t('عرض الإعلانات النشطة','Serve active ads')}</small></span><input id="set-ads" type="checkbox" ${s.advertising_enabled?'checked':''}></label><label class="setting-row"><span><strong>${t('وضع الصيانة','Maintenance mode')}</strong><small>${t('إشارة تشغيلية للمنصة','Operational flag')}</small></span><input id="set-maintenance" type="checkbox" ${s.maintenance_mode?'checked':''}></label></section><section class="card card-pad form-stack"><div class="field"><label>${t('الحد اليومي لطلبات التبادل','Daily exchange request limit')}</label><input id="set-exchanges" class="input" type="number" value="${Number(s.max_exchange_requests_day||20)}"></div><div class="field"><label>${t('أقصى طول للرسالة','Max message length')}</label><input id="set-message" class="input" type="number" value="${Number(s.max_message_length||4000)}"></div><div class="notice warning">${t('الـmaintenance flag محفوظ في الخادم. إضافة حماية شاملة للقراءة العامة يمكن تشغيلها لاحقًا حسب بيئة النشر.','The maintenance flag is persisted server-side and can be wired to deployment-wide blocking when desired.')}</div></section></div>`;}
async function saveAdminSettings(){try{const data=await api('/admin/settings',{method:'PATCH',body:JSON.stringify({registration_enabled:document.getElementById('set-registration').checked,advertising_enabled:document.getElementById('set-ads').checked,maintenance_mode:document.getElementById('set-maintenance').checked,max_exchange_requests_day:Number(document.getElementById('set-exchanges').value),max_message_length:Number(document.getElementById('set-message').value)})});adminCache.settings=data;toast(t('تم حفظ الإعدادات','Settings saved'),'success');}catch(e){toast(e.message,'error');}}

async function loadAdmin(kind){if(!isAdmin())return;try{if(kind==='analytics'||kind==='dashboard')adminCache.analytics=await api('/admin/analytics');if(kind==='users')adminCache.users=await api('/admin/users');if(kind==='reports')adminCache.reports=await api('/admin/reports');if(kind==='jobs')adminCache.jobs=await api('/admin/jobs');if(kind==='exchanges')adminCache.exchanges=await api('/admin/exchanges');if(kind==='ads')adminCache.ads=await api('/admin/ads');if(kind==='reviews')adminCache.reviews=await api('/admin/reviews');if(kind==='skills')adminCache.skills=await api('/admin/skills');if(kind==='categories')adminCache.categories=await api('/admin/categories');if(kind==='actions')adminCache.actions=await api('/admin/actions');if(kind==='settings')adminCache.settings=await api('/admin/settings');state.skipAdminFetch=true;render();if(kind==='users')renderAdminUsers();}catch(e){toast(e.message,'error');}}

function render(){
  const rawHash=location.hash.slice(1);
  if(rawHash.includes('access_token=')){const params=new URLSearchParams(rawHash);const token=params.get('access_token');if(token){state.recoveryToken=token;sessionStorage.setItem('ss-recovery-token',token);}state.route='reset-password';}else{state.route=rawHash||'home';}
  document.documentElement.dataset.theme=state.theme;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';
  const r=state.route.split('?')[0];
  if(r.startsWith('admin')&&!isAdmin()){document.getElementById('app').innerHTML=shell(`<div class="forbidden card"><div class="empty-icon">${icon('shield',34)}</div><h2>${t('لا توجد صلاحية','Access denied')}</h2><p>${t('المنطقة دي للإدارة فقط.','This area is restricted to admins.')}</p><a class="btn btn-primary" href="#home">${t('العودة للمنصة','Back to platform')}</a></div>`,false,{assistant:false});return;}
  let out='';
  if(r==='home')out=home(); else if(r==='browse')out=browse(); else if(r==='jobs')out=jobsPage(); else if(r==='exchanges')out=exchangesPage(); else if(r==='chat')out=chatPage(); else if(r==='notifications')out=notificationsPage(); else if(r==='profile')out=profile(); else if(r.startsWith('user/'))out=profile(r.split('/')[1]); else if(r.startsWith('exchange/'))out=exchangeWorkspace(r.split('/')[1]); else if(r==='login')out=loginPage(); else if(r==='register')out=registerPage(); else if(r==='forgot-password')out=forgotPasswordPage(); else if(r==='reset-password')out=resetPasswordPage(); else if(r==='admin')out=adminDashboard(); else if(r==='admin/analytics')out=shell(adminAnalytics(),true,{assistant:false}); else if(r==='admin/settings')out=shell(adminSettingsPage(),true,{assistant:false}); else if(r.startsWith('admin/'))out=adminTablePage(r); else out=home();
  document.getElementById('app').innerHTML=out;
  const gs=document.getElementById('global-search');if(gs)gs.onkeydown=e=>{if(e.key==='Enter'){const q=gs.value.trim();go(`browse${q?`?q=${encodeURIComponent(q)}`:''}`);}};
  if(r==='browse')setTimeout(filterBrowse,0);
  if(r==='chat')setTimeout(renderChatMessages,0);
  if(r.startsWith('user/')){if(state.skipProfileFetch){state.skipProfileFetch=false;}else setTimeout(()=>loadProfile(r.split('/')[1]),20);}
  const adminKind={'admin':'dashboard','admin/users':'users','admin/reports':'reports','admin/jobs':'jobs','admin/exchanges':'exchanges','admin/ads':'ads','admin/reviews':'reviews','admin/skills':'skills','admin/categories':'categories','admin/analytics':'analytics','admin/actions':'actions','admin/settings':'settings'}[r];
  if(adminKind){if(state.skipAdminFetch){state.skipAdminFetch=false;}else setTimeout(()=>loadAdmin(adminKind),0);}
}

function connectRealtime(){if(!window.io||!authToken())return;realtimeSocket?.disconnect();realtimeSocket=io({auth:{token:authToken()}});realtimeSocket.on('message:new',m=>{messages.push(normalizeMessage(m));if(state.route==='chat')renderChatMessages();});}

window.addEventListener('hashchange',render);
window.addEventListener('DOMContentLoaded',async()=>{document.documentElement.dataset.theme=state.theme;connectRealtime();render();await hydrateBackend();});
