'use strict';
/* ───────── Admin center ───────── */
const can = perm => { const p = state.user?.permissions || []; return p.includes('*') || p.includes(perm) || p.includes(perm.split('.')[0]); };
const ADMIN_TABS = [
  ['dash', 'نظرة عامة', 'chart', 'analytics'], ['users', 'المستخدمون', 'users', 'users.view'], ['listings', 'العروض والطلبات', 'swap', 'listings'], ['reports', 'البلاغات', 'flag', 'reports.view'], ['exchanges', 'التبادلات', 'swap', 'exchanges.view'],
  ['ads', 'إعلانات الشركات', 'ad', 'ads'], ['jobs', 'الوظائف', 'brief', 'jobs'], ['skills', 'المهارات', 'tag', 'taxonomy'], ['reviews', 'التقييمات', 'star', 'reviews'], ['logs', 'سجل الإجراءات', 'log', 'logs'], ['settings', 'الإعدادات', 'gear', 'settings'], ['about', 'عن المشروع', 'info', 'settings'],
];
const ACTION_AR = { suspended: 'إيقاف مؤقت', banned: 'حظر', closed: 'إغلاق حساب', reactivate: 'إعادة تفعيل', verify: 'توثيق', unverify: 'إلغاء توثيق', role_change: 'تغيير دور', ad_create: 'إنشاء إعلان', ad_update: 'تعديل إعلان', ad_delete: 'حذف إعلان', report_dismiss: 'رفض بلاغ', report_resolve: 'حل بلاغ', report_warn: 'تحذير', report_suspend: 'إيقاف عبر بلاغ', report_close: 'إغلاق عبر بلاغ', report_ban: 'حظر عبر بلاغ', report_investigate: 'بدء مراجعة', job_moderation: 'مراجعة وظيفة', view_report_chat: 'اطلاع على محادثة مُبلّغ عنها', settings_update: 'تعديل الإعدادات', about_update: 'تعديل صفحة عن المشروع', exchange_status: 'تغيير حالة تبادل', listing_moderation: 'إدارة منشور' };

async function viewAdmin(el, [tab]) {
  const tabs = ADMIN_TABS.filter(t => can(t[3]));
  if (!tabs.length) { el.innerHTML = `<div class="card">${emptyState('shield', 'ليس لديك صلاحية الدخول للوحة الإدارة.')}</div>`; return; }
  tab = tabs.find(t => t[0] === tab) ? tab : tabs[0][0];
  el.innerHTML = pageHead('لوحة الإدارة', `${L.role[state.user.role]} — كل إجراء يُسجَّل في سجل المراجعة`) + `<div class="tabs" role="tablist">${tabs.map(t => `<a class="tab" role="tab" aria-selected="${t[0] === tab}" href="#/admin/${t[0]}" style="display:inline-flex;gap:6px;align-items:center;text-decoration:none">${icon(t[2])}${t[1]}</a>`).join('')}</div><div id="adm">${skeletons(3)}</div>`;
  const box = $('#adm');
  try { await ({ dash: admDash, users: admUsers, listings: admListings, reports: admReports, exchanges: admExchanges, ads: admAds, jobs: admJobs, skills: admSkills, reviews: admReviews, logs: admLogs, settings: admSettings, about: admAbout })[tab](box); }
  catch (e) { box.innerHTML = `<div class="alert err">${icon('info')}${esc(errMsg(e))}</div>`; }
}
const tbl = (head, rows, empty = 'لا توجد بيانات') => rows.length ? `<div class="table-wrap"><table><thead><tr>${head.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>` : `<div class="card">${emptyState('log', empty)}</div>`;

/* ── dashboard ── */
async function admDash(box) {
  const a = await get('/admin/analytics');
  const cards = [
    ['users', a.total_users, 'إجمالي الأعضاء', '#/admin/users'],
    ['users', a.active_users, 'أعضاء نشطون', '#/admin/users'],
    ['swap', a.published_listings || 0, 'منشورات نشطة', '#/admin/listings'],
    ['send', a.pending_proposals || 0, 'عروض تبادل معلقة', '#/admin/listings'],
    ['flag', a.open_reports, 'بلاغات تحتاج مراجعة', '#/admin/reports'],
    ['swap', a.completed_exchanges, 'تبادلات مكتملة', '#/admin/exchanges'],
    ['ad', a.active_ads, 'إعلانات نشطة', '#/admin/ads'],
    ['chat', a.messages_7d, 'رسائل آخر 7 أيام', ''],
  ];
  const S = ([ic,n,l,href]) => `<a class="admin-stat-v3 card ${href?'clickable':''}" href="${href || '#/admin'}"><span class="stat-ico">${icon(ic)}</span><div><small>${l}</small><b>${arNum(n)}</b></div>${href ? icon('arrow','stat-arrow') : ''}</a>`;
  const max = Math.max(1, ...a.growth.map(g => Math.max(Number(g.users) || 0, Number(g.exchanges) || 0)));
  box.innerHTML = `<div class="admin-hero"><div><span class="eyebrow">KHOD & HAT CONTROL CENTER</span><h1>السيطرة التشغيلية على المنصة</h1><p>إدارة الأعضاء والمحتوى والتبادل والإعلانات والإعدادات من مكان واحد، وكل قرار حساس يُسجَّل في سجل المراجعة.</p></div><div class="admin-health"><span class="health-dot"></span><div><b>حالة النظام</b><small>الحركة طبيعية · ${a.active_users} عضو نشط</small></div></div></div>
    <div class="admin-stat-grid">${cards.map(S).join('')}</div>
    <div class="admin-grid-v3"><section class="card"><div class="section-heading"><div><span class="eyebrow">GROWTH</span><h2>نمو المنصة</h2></div><a class="btn sm ghost" href="#/admin">لوحة التحليلات ${icon('arrow')}</a></div><div class="bars-v3">${a.growth.map(g => `<div class="bar-col"><div class="bar-stack"><i style="height:${(g.users/max)*100}%"></i><i class="exchange-bar" style="height:${(g.exchanges/max)*100}%"></i></div><span>${esc(g.month.slice(5))}</span></div>`).join('')}</div><div class="row wrap gap-l small muted mt"><span><i class="legend-dot"></i> أعضاء</span><span><i class="legend-dot exchange"></i> تبادلات</span></div></section>
      <section class="card"><div class="section-heading"><div><span class="eyebrow">EXCHANGE ENGINE</span><h2>صحة محرك التبادل</h2></div></div><div class="health-list"><div><span>عروض منشورة</span><b>${arNum(a.live_offers || 0)}</b></div><div><span>طلبات منشورة</span><b>${arNum(a.live_needs || 0)}</b></div><div><span>عروض تنتظر الرد</span><b>${arNum(a.pending_proposals || 0)}</b></div><div><span>تبادلات متنازع عليها</span><b>${arNum(a.disputed_exchanges || 0)}</b></div></div><a class="btn primary block mt" href="#/admin/listings">فتح مركز العروض والطلبات</a></section></div>`;
}

/* ── users: suspend / close / ban / reactivate ── */
async function admUsers(box) {
  const f = { search: '', status: '', role: '' };
  box.innerHTML = `<div class="row wrap mb"><input class="input grow" id="us" placeholder="ابحث بالاسم أو البريد أو الهاتف…" style="max-width:360px"><select class="input" id="ust" style="max-width:180px"><option value="">كل الحالات</option>${Object.entries(L.account).map(([k, v]) => `<option value="${k}">${v[0]}</option>`).join('')}</select><select class="input" id="ur" style="max-width:180px"><option value="">كل الأدوار</option><option value="staff">فريق الإدارة</option></select></div><div id="ul">${skeletons(2)}</div>`;
  const run = async () => {
    const p = new URLSearchParams(Object.entries(f).filter(([, v]) => v)); const list = await get(`/admin/users?${p}`);
    $('#ul').innerHTML = tbl(['المستخدم', 'الدور', 'الحالة', 'التقييم', 'بلاغات ضده', 'انضم', ''], list.map(u => `<tr><td><div class="row">${avatar(u, 's')}<div><b>${esc(u.name)}</b> ${u.is_verified ? verifiedBadge : ''}<div class="xs muted" dir="ltr" style="text-align:start">${esc(u.email)}</div></div></div></td><td>${L.role[u.role] || u.role}</td><td>${chip(L.account, u.status)}${u.status_until ? `<div class="xs muted">حتى ${fmtDate(u.status_until)}</div>` : ''}</td><td>${Number(u.rating).toFixed(1)}</td><td>${u.reports_against ? `<span class="chip r">${arNum(u.reports_against)}</span>` : '0'}</td><td class="xs">${fmtDate(u.created_at)}</td><td><button class="btn sm" data-u="${esc(u.id)}">إدارة</button></td></tr>`), 'لا يوجد مستخدمون مطابقون');
    $$('[data-u]', $('#ul')).forEach(b => b.onclick = () => userDrawer(b.dataset.u, run));
  };
  $('#us').oninput = debounce(e => { f.search = e.target.value.trim(); run(); }); $('#ust').onchange = e => { f.status = e.target.value; run(); }; $('#ur').onchange = e => { f.role = e.target.value; run(); }; await run();
}
async function userDrawer(id, done) {
  const u = await get(`/admin/users/${id}`); const self = id === state.user.id;
  const m = openModal({ title: u.name, wide: true, body: `<div class="row wrap" style="gap:16px">${avatar(u, 'l')}<div class="grow"><h2 style="margin:0">${esc(u.name)} ${u.is_verified ? verifiedBadge : ''}</h2><div class="muted small" dir="ltr" style="text-align:start">${esc(u.email)} ${u.phone ? '· ' + esc(u.phone) : ''}</div><div class="row gap-s wrap mt">${chip(L.account, u.status)}<span class="chip n">${L.role[u.role]}</span><span class="chip n">${arNum(u.stats.exchanges)} تبادل</span><span class="chip n">${arNum(u.stats.connections)} اتصال</span><span class="chip n">تقييم ${Number(u.stats.rating).toFixed(1)}</span></div>${u.status !== 'active' && u.status_reason ? `<div class="alert warn mt">السبب المسجّل: ${esc(u.status_reason)}</div>` : ''}</div></div>
    ${!self ? `<div class="card flat mt" style="background:var(--surface-2)"><h3>إجراءات الحساب</h3><div class="row wrap">${u.status !== 'active' ? '<button class="btn success" data-s="active">إعادة تفعيل الحساب</button>' : '<button class="btn" data-s="suspended">إيقاف مؤقت</button><button class="btn" data-s="closed">إغلاق الحساب</button><button class="btn danger" data-s="banned">حظر نهائي</button>'}${can('users.moderate') ? `<button class="btn ghost" id="vf">${u.is_verified ? 'إلغاء التوثيق' : 'توثيق الحساب'}</button>` : ''}${can('users.manage') ? '<button class="btn ghost" id="rl">تغيير الدور</button><button class="btn ghost" id="pr">رابط استعادة كلمة المرور</button><button class="btn ghost" id="dl" style="color:var(--danger)">حذف نهائي</button>' : ''}</div></div>` : '<div class="alert info mt">هذا حسابك — لا يمكنك تغيير حالته من هنا.</div>'}
    <div class="grid mt" style="grid-template-columns:repeat(auto-fit,minmax(280px,1fr))"><div class="card flat"><h3>بلاغات ضد المستخدم (${arNum(u.reports.length)})</h3>${u.reports.length ? u.reports.map(r => `<div class="small" style="padding:6px 0;border-bottom:1px solid var(--border)"><b>${esc(r.reason)}</b> ${chip(L.report, r.status)}<div class="xs muted">${L.target[r.target_type]} · من ${esc(r.reporter_name)} · ${ago(r.created_at)}</div></div>`).join('') : '<p class="muted small">لا يوجد.</p>'}</div>
      <div class="card flat"><h3>آخر إجراءات إدارية</h3>${u.logs.length ? u.logs.map(l => `<div class="small" style="padding:6px 0;border-bottom:1px solid var(--border)"><b>${ACTION_AR[l.action] || esc(l.action)}</b> — ${esc(l.note)}<div class="xs muted">${esc(l.admin_name)} · ${ago(l.created_at)}</div></div>`).join('') : '<p class="muted small">لا يوجد.</p>'}</div></div>` });
  $$('[data-s]', m.el).forEach(b => b.onclick = () => statusDialog(u, b.dataset.s, () => { m.close(); done(); }));
  $('#vf', m.el)?.addEventListener('click', async () => { await api(`/admin/users/${id}/verification`, { method: 'PATCH', body: { is_verified: !u.is_verified } }); toast('تم التحديث', 'ok'); m.close(); done(); });
  $('#rl', m.el)?.addEventListener('click', () => { const r = openModal({ title: 'تغيير الدور', body: `<select class="input" id="nr">${Object.entries(L.role).map(([k, v]) => `<option value="${k}" ${u.role === k ? 'selected' : ''}>${v}</option>`).join('')}</select>`, footer: '<button class="btn primary" id="ok">حفظ</button>' }); r.$('#ok').onclick = e => busy(e.currentTarget, async () => { await api(`/admin/users/${id}/role`, { method: 'PATCH', body: { role: r.$('#nr').value } }); toast('تم تغيير الدور', 'ok'); r.close(); m.close(); done(); }); });
  $('#pr', m.el)?.addEventListener('click', e => busy(e.currentTarget, async () => { const j = await api(`/admin/users/${id}/password-reset`, { method: 'POST' }); const l = j.data.action_link; openModal({ title: 'رابط الاستعادة', body: `<p class="small muted">أرسله للمستخدم بشكل آمن. الرابط يعمل مرة واحدة.</p><input class="input" readonly dir="ltr" value="${esc(l || '')}" onfocus="this.select()">` }); }));
  $('#dl', m.el)?.addEventListener('click', async () => { if (await confirmBox({ title: 'حذف الحساب نهائيًا', message: `سيتم حذف حساب <b>${esc(u.name)}</b> وكل بياناته ولا يمكن التراجع. الأفضل استخدام "إغلاق الحساب". متأكد؟`, confirmText: 'احذف نهائيًا', danger: true })) { await api(`/admin/users/${id}`, { method: 'DELETE' }).catch(e => toast(errMsg(e), 'err')); toast('تم الحذف', 'ok'); m.close(); done(); } });
}
function statusDialog(u, status, done) {
  const T = { suspended: ['إيقاف الحساب مؤقتًا', 'btn'], closed: ['إغلاق الحساب', 'btn'], banned: ['حظر الحساب نهائيًا', 'btn danger'], active: ['إعادة تفعيل الحساب', 'btn success'] }[status];
  const m = openModal({ title: `${T[0]} — ${u.name}`, body: `${status !== 'active' ? `<div class="alert warn">${icon('info')}سيُمنع المستخدم من الدخول فورًا ويُرسل له إشعار بالسبب.</div><div class="field mt"><label for="sr">السبب (يظهر للمستخدم) *</label><textarea class="input" id="sr" maxlength="500" placeholder="مثال: مخالفة قواعد المجتمع — طلب بيانات دفع من أعضاء."></textarea></div>${status === 'suspended' ? '<div class="field"><label for="sdays">مدة الإيقاف (أيام) — اتركها فارغة لإيقاف مفتوح</label><input class="input" id="sdays" type="number" min="1" max="365" value="7"></div>' : ''}` : '<p>سيتمكن المستخدم من الدخول مجددًا.</p>'}`, footer: `<button class="btn ghost" data-x2>إلغاء</button><button class="${T[1]}" id="ok">${T[0]}</button>` });
  m.$('[data-x2]').onclick = m.close;
  m.$('#ok').onclick = e => busy(e.currentTarget, async () => { const reason = m.$('#sr')?.value.trim() || ''; if (status !== 'active' && !reason) throw new Error('اكتب سبب الإجراء'); const d = Number(m.$('#sdays')?.value) || undefined; await api(`/admin/users/${u.id}/status`, { method: 'PATCH', body: { status, reason, days: status === 'suspended' ? d : undefined } }); toast('تم تنفيذ الإجراء', 'ok'); m.close(); done(); });
}

/* ── reports (users, exchanges, messages) ── */
async function admReports(box) {
  const f = { status: 'active', type: '' };
  box.innerHTML = `<div class="row wrap mb"><select class="input" id="rs" style="max-width:200px"><option value="active">تحتاج مراجعة</option><option value="">كل البلاغات</option><option value="resolved">تم حلها</option><option value="dismissed">مرفوضة</option></select><select class="input" id="rt" style="max-width:200px"><option value="">كل الأنواع</option><option value="exchange">بلاغات التبادل</option><option value="user">بلاغات المستخدمين</option><option value="message">بلاغات الرسائل</option></select></div><div id="rl">${skeletons(2)}</div>`;
  const run = async () => { const p = new URLSearchParams(Object.entries(f).filter(([, v]) => v)); const list = await get(`/admin/reports?${p}`);
    $('#rl').innerHTML = tbl(['النوع', 'السبب', 'المُبلِّغ', 'المُبلَّغ عنه', 'الحالة', 'التاريخ', ''], list.map(r => `<tr><td><span class="chip b">${L.target[r.target_type] || r.target_type}</span></td><td><b>${esc(r.reason)}</b></td><td>${esc(r.reporter_name)}</td><td>${esc(r.reported_name || '—')} ${r.reports_against > 1 ? `<span class="chip r" title="عدد البلاغات ضده">${arNum(r.reports_against)}</span>` : ''} ${r.reported_status && r.reported_status !== 'active' ? chip(L.account, r.reported_status) : ''}</td><td>${chip(L.report, r.status)}</td><td class="xs">${ago(r.created_at)}</td><td><button class="btn sm primary" data-r="${esc(r.id)}">مراجعة</button></td></tr>`), 'لا توجد بلاغات 🎉'.replace(' 🎉', ''));
    $$('[data-r]', $('#rl')).forEach(b => b.onclick = () => reportDrawer(b.dataset.r, run)); };
  $('#rs').onchange = e => { f.status = e.target.value; run(); }; $('#rt').onchange = e => { f.type = e.target.value; run(); }; await run();
}
async function reportDrawer(id, done) {
  const r = await get(`/admin/reports/${id}`); const ex = r.context.exchange; const msgs = r.context.messages; const closed = ['resolved', 'dismissed'].includes(r.status); const canMod = can('users.moderate') && r.reported_user_id;
  const m = openModal({ title: `بلاغ: ${r.reason}`, wide: true, body: `<div class="row wrap gap-s">${chip(L.report, r.status)}<span class="chip b">${L.target[r.target_type]}</span><span class="xs muted">${fmtDate(r.created_at)}</span></div>
    <div class="grid mt" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr))"><div class="card flat" style="background:var(--surface-2)"><div class="xs muted">المُبلِّغ</div><b>${esc(r.reporter_name)}</b></div><div class="card flat" style="background:var(--danger-50)"><div class="xs muted">المُبلَّغ عنه</div><b>${esc(r.reported_name || '—')}</b> ${r.reported_status ? chip(L.account, r.reported_status) : ''}</div></div>
    ${r.description ? `<div class="card flat mt"><div class="xs muted">تفاصيل البلاغ</div><p style="margin:4px 0 0;white-space:pre-wrap">${esc(r.description)}</p></div>` : ''}
    ${ex ? `<div class="card flat mt"><h3>التبادل المرتبط</h3><div class="small">${esc(ex.sender_name)} ↔ ${esc(ex.receiver_name)} · ${esc(ex.offered_skill)} مقابل ${esc(ex.requested_skill)} ${chip(L.exchange, ex.status)}</div><ul class="timeline mt">${ex.events.map(e => `<li><span class="small">${esc(e.note || e.event_type)}</span> <span class="xs muted">${ago(e.created_at)}</span></li>`).join('')}</ul></div>` : ''}
    ${msgs ? `<div class="card flat mt"><h3>سياق المحادثة المُبلَّغ عنها</h3><p class="xs muted">يظهر فقط للرسالة المُبلَّغ عنها، ويشمل الرسائل الصوتية (روابط مؤقتة 15 دقيقة)، وفتحها مُسجَّل في سجل المراجعة.</p>${msgs.map(x => `<div class="small" style="padding:4px 0;${x.id === r.target_id ? 'background:var(--danger-50);border-radius:8px;padding:6px 8px' : ''}"><b>${esc(x.sender_name)}</b> <span class="xs muted">${fmtTime(x.sent_at)}</span><div style="white-space:pre-wrap">${x.kind === 'voice' ? (x.audio_url ? `<audio controls preload="none" src="${esc(x.audio_url)}" style="width:100%;max-width:340px"></audio> <span class="xs muted">${fmtDur(x.audio_seconds || 0)}</span>` : '<span class="muted">🎤 التسجيل الصوتي غير متاح</span>') : esc(x.body)}</div></div>`).join('')}</div>` : ''}
    ${r.prior_reports.length ? `<div class="card flat mt"><h3>بلاغات سابقة ضد نفس الحساب (${arNum(r.prior_reports.length)})</h3>${r.prior_reports.map(p => `<div class="small row between" style="padding:4px 0"><span>${esc(p.reason)}</span>${chip(L.report, p.status)}</div>`).join('')}</div>` : ''}
    ${r.admin_note ? `<div class="alert info mt">ملاحظة سابقة: ${esc(r.admin_note)}</div>` : ''}
    ${!closed ? `<div class="field mt"><label for="an">ملاحظة / سبب الإجراء</label><textarea class="input" id="an" maxlength="1000" placeholder="تُسجَّل في السجل، وتظهر للمستخدم عند الإيقاف/الإغلاق."></textarea></div><div class="field" id="dayswrap"><label for="ad">مدة الإيقاف المؤقت (أيام)</label><input class="input" id="ad" type="number" min="1" max="365" value="7" style="max-width:140px"></div>` : ''}`,
    footer: closed ? '<button class="btn ghost" data-x2>إغلاق</button>' : `<button class="btn ghost" data-act="dismiss">رفض البلاغ</button><button class="btn ghost" data-act="investigate">قيد المراجعة</button><button class="btn" data-act="warn">تحذير المستخدم</button>${canMod ? '<button class="btn" data-act="suspend">إيقاف مؤقت</button><button class="btn" data-act="close">إغلاق الحساب</button><button class="btn danger" data-act="ban">حظر</button>' : ''}<button class="btn success" data-act="resolve">تم الحل</button>` });
  m.$('[data-x2]')?.addEventListener('click', m.close);
  $$('[data-act]', m.el).forEach(b => b.onclick = () => busy(b, async () => { const act = b.dataset.act; const note = m.$('#an').value.trim(); if (['suspend', 'close', 'ban'].includes(act) && !note) throw new Error('اكتب سبب الإجراء — سيظهر للمستخدم'); if (['close', 'ban'].includes(act) && !(await confirmBox({ title: act === 'ban' ? 'حظر الحساب' : 'إغلاق الحساب', message: `سيتم ${act === 'ban' ? 'حظر' : 'إغلاق'} حساب <b>${esc(r.reported_name)}</b> فورًا.`, confirmText: 'تنفيذ', danger: true }))) return; await api(`/admin/reports/${id}`, { method: 'PATCH', body: { action: act, note, days: act === 'suspend' ? Number(m.$('#ad').value) || undefined : undefined } }); toast('تم تنفيذ الإجراء', 'ok'); m.close(); done(); }));
}

/* ── exchanges ── */
async function admExchanges(box) {
  const list = await get('/admin/exchanges'); const edit = can('exchanges');
  box.innerHTML = tbl(['الأطراف', 'المهارات', 'الحالة', 'بلاغات', 'آخر تحديث', ''], list.map(x => `<tr><td>${esc(x.sender_name)} ↔ ${esc(x.receiver_name)}</td><td class="small">${esc(x.offered_skill)} / ${esc(x.requested_skill)}</td><td>${chip(L.exchange, x.status)}</td><td>${x.reports ? `<span class="chip r">${arNum(x.reports)}</span>` : '0'}</td><td class="xs">${ago(x.updated_at)}</td><td>${edit ? `<select class="input" data-x="${esc(x.id)}" style="min-height:36px;padding:2px 8px"><option value="">تغيير الحالة…</option>${Object.entries(L.exchange).map(([k, v]) => `<option value="${k}">${v[0]}</option>`).join('')}</select>` : ''}</td></tr>`), 'لا توجد تبادلات');
  $$('[data-x]', box).forEach(s => s.onchange = async () => { if (!s.value) return; if (!(await confirmBox({ title: 'تغيير حالة التبادل', message: 'سيتم إشعار الطرفين بالتغيير.' }))) { s.value = ''; return; } await api(`/admin/exchanges/${s.dataset.x}/status`, { method: 'PATCH', body: { status: s.value } }).catch(e => toast(errMsg(e), 'err')); admExchanges(box); });
}

/* ── company ads ── */
async function admAds(box) {
  const list = await get('/admin/ads');
  box.innerHTML = `<div class="row between mb"><p class="muted small" style="margin:0">أنشئ إعلانًا لشركة وحدّد مكان ظهوره ومدته. تُحسب المشاهدات والنقرات تلقائيًا.</p><button class="btn primary" id="na">${icon('plus')} إعلان جديد</button></div>` +
    tbl(['الإعلان', 'الشركة', 'المكان', 'الحالة', 'مشاهدات', 'نقرات', 'المدة', ''], list.map(a => `<tr><td><b>${esc(a.title)}</b></td><td>${esc(a.advertiser_name)}</td><td class="xs">${L.placement[a.placement] || a.placement}</td><td>${chip({ active: ['نشط', 'g'], paused: ['متوقف مؤقتًا', 'w'], disabled: ['معطّل', 'n'] }, a.status)}</td><td>${arNum(a.impressions)}</td><td>${arNum(a.clicks)} <span class="xs muted">${a.impressions ? '(' + (a.clicks / a.impressions * 100).toFixed(1) + '%)' : ''}</span></td><td class="xs">${a.start_at ? fmtDate(a.start_at) : '—'} → ${a.end_at ? fmtDate(a.end_at) : 'مفتوح'}</td><td class="row gap-s"><button class="btn sm" data-e="${esc(a.id)}">تعديل</button><button class="btn sm ghost" data-t="${esc(a.id)}" data-st="${a.status}">${a.status === 'active' ? 'إيقاف' : 'تفعيل'}</button><button class="btn sm ghost" data-d="${esc(a.id)}" aria-label="حذف" style="color:var(--danger)">${icon('trash')}</button></td></tr>`), 'لا توجد إعلانات بعد');
  $('#na').onclick = () => adForm(null, () => admAds(box));
  $$('[data-e]', box).forEach(b => b.onclick = () => adForm(list.find(a => a.id === b.dataset.e), () => admAds(box)));
  $$('[data-t]', box).forEach(b => b.onclick = async () => { await api(`/admin/ads/${b.dataset.t}`, { method: 'PATCH', body: { status: b.dataset.st === 'active' ? 'paused' : 'active' } }); admAds(box); });
  $$('[data-d]', box).forEach(b => b.onclick = async () => { if (await confirmBox({ title: 'حذف الإعلان', message: 'سيُحذف الإعلان وإحصاءاته نهائيًا.', confirmText: 'حذف', danger: true })) { await api(`/admin/ads/${b.dataset.d}`, { method: 'DELETE' }); admAds(box); } });
}
function adForm(ad, done) {
  const v = k => esc(ad?.[k] ?? ''); const dt = k => ad?.[k] ? new Date(ad[k]).toISOString().slice(0, 16) : '';
  const m = openModal({ title: ad ? 'تعديل الإعلان' : 'إعلان شركة جديد', wide: true, body: `<div class="grid2"><div class="field"><label for="at">عنوان الإعلان *</label><input class="input" id="at" maxlength="180" value="${v('title')}"></div><div class="field"><label for="an">اسم الشركة *</label><input class="input" id="an" maxlength="160" value="${v('advertiser_name')}"></div></div>
    <div class="field"><label for="ads">النص</label><textarea class="input" id="ads" maxlength="1000">${v('description')}</textarea></div>
    <div class="grid2"><div class="field"><label for="au">رابط الإعلان</label><input class="input" id="au" type="url" dir="ltr" style="text-align:start" placeholder="https://company.com" value="${v('target_url')}"></div><div class="field"><label for="ac">نص الزر</label><input class="input" id="ac" maxlength="60" value="${esc(ad?.cta_label || 'اعرف أكثر')}"></div></div>
    <div class="grid2"><div class="field"><label>صورة الإعلان</label><input type="file" id="ai" accept="image/jpeg,image/png,image/webp" class="input" style="padding:8px"><input type="hidden" id="aiu" value="${v('image_url')}"><span class="hint" id="aih">${ad?.image_url ? 'توجد صورة حالية' : 'اختياري — تُضغط تلقائيًا'}</span></div><div class="field"><label>شعار الشركة</label><input type="file" id="al" accept="image/jpeg,image/png,image/webp" class="input" style="padding:8px"><input type="hidden" id="alu" value="${v('logo_url')}"><span class="hint" id="alh">${ad?.logo_url ? 'يوجد شعار حالي' : 'اختياري'}</span></div></div>
    <div class="grid2"><div class="field"><label for="ap">مكان الظهور</label><select class="input" id="ap">${Object.entries(L.placement).map(([k, t]) => `<option value="${k}" ${ad?.placement === k ? 'selected' : ''}>${t}</option>`).join('')}</select></div><div class="field"><label for="as">الحالة</label><select class="input" id="as"><option value="active" ${ad?.status === 'active' ? 'selected' : ''}>نشط</option><option value="paused" ${ad?.status === 'paused' ? 'selected' : ''}>متوقف مؤقتًا</option><option value="disabled" ${ad?.status === 'disabled' ? 'selected' : ''}>معطّل</option></select></div></div>
    <div class="grid2"><div class="field"><label for="a1">يبدأ</label><input class="input" id="a1" type="datetime-local" value="${dt('start_at')}"></div><div class="field"><label for="a2">ينتهي</label><input class="input" id="a2" type="datetime-local" value="${dt('end_at')}"></div></div><div class="field"><label for="apr">الأولوية (0-100، الأعلى يظهر أولًا)</label><input class="input" id="apr" type="number" min="0" max="100" value="${ad?.priority ?? 0}" style="max-width:140px"></div>`, footer: '<button class="btn ghost" data-x2>إلغاء</button><button class="btn primary" id="ok">حفظ الإعلان</button>' });
  m.$('[data-x2]').onclick = m.close;
  for (const [fid, hid, max] of [['ai', 'aiu', 1100], ['al', 'alu', 300]]) m.$(`#${fid}`).onchange = async e => { const f = e.target.files[0]; if (!f) return; try { const r = await api('/admin/uploads/ad-image', { method: 'POST', body: { data_url: await resizeImage(f, max, .82) } }); m.$(`#${hid}`).value = r.data.url; m.$(`#${fid === 'ai' ? 'aih' : 'alh'}`).textContent = 'تم رفع الصورة ✓'.replace(' ✓', ''); toast('تم رفع الصورة', 'ok'); } catch (x) { toast(errMsg(x), 'err'); } };
  m.$('#ok').onclick = e => busy(e.currentTarget, async () => { const iso = id => m.$(id).value ? new Date(m.$(id).value).toISOString() : null;
    const body = { title: m.$('#at').value.trim(), advertiser_name: m.$('#an').value.trim(), description: m.$('#ads').value.trim(), target_url: m.$('#au').value.trim(), cta_label: m.$('#ac').value.trim() || 'اعرف أكثر', image_url: m.$('#aiu').value, logo_url: m.$('#alu').value, placement: m.$('#ap').value, status: m.$('#as').value, priority: Number(m.$('#apr').value) || 0, start_at: iso('#a1'), end_at: iso('#a2') };
    if (body.title.length < 2 || body.advertiser_name.length < 2) throw new Error('اكتب العنوان واسم الشركة');
    await api(ad ? `/admin/ads/${ad.id}` : '/admin/ads', { method: ad ? 'PATCH' : 'POST', body }); toast('تم حفظ الإعلان', 'ok'); m.close(); done(); });
}

/* ── universal exchange listings ── */
function adminListingEditor(x, box) {
  const skillOpts = state.skills.map(s => `<option value="${esc(s.id)}" ${String(x.skill_id||'')===String(s.id)?'selected':''}>${esc(s.name)}</option>`).join('');
  const catOpts = state.cats.map(c => `<option value="${esc(c.id)}" ${String(x.category_id||'')===String(c.id)?'selected':''}>${esc(c.name)}</option>`).join('');
  const m = openModal({ title: 'تعديل منشور التبادل', wide: true, body: `<div class="modal-grid">
    <section><div class="field"><label>النوع</label><div class="choice-grid"><label class="choice ${x.mode==='offer'?'selected':''}"><input type="radio" name="amode" value="offer" ${x.mode==='offer'?'checked':''}><span><b>أقدّم</b><small>عرض شيء أملكه</small></span></label><label class="choice ${x.mode==='need'?'selected':''}"><input type="radio" name="amode" value="need" ${x.mode==='need'?'checked':''}><span><b>أحتاج</b><small>طلب شيء أريده</small></span></label></div></div>
    <div class="field"><label>نوع التبادل</label><select class="input" id="aa">${Object.entries(EX_ASSETS).map(([k,v]) => `<option value="${k}" ${x.asset_type===k?'selected':''}>${v[0]}</option>`).join('')}</select></div>
    <div class="field"><label>العنوان</label><input class="input" id="at" maxlength="180" value="${esc(x.title)}"></div>
    <div class="field"><label>التفاصيل</label><textarea class="input" id="ad" maxlength="4000">${esc(x.description||'')}</textarea></div></section>
    <section><div class="field"><label>التصنيف</label><select class="input" id="ac"><option value="">بدون تصنيف</option>${catOpts}</select></div><div class="field"><label>المهارة</label><select class="input" id="as"><option value="">ليست مهارة محددة</option>${skillOpts}</select></div>
    <div class="grid2"><div class="field"><label>المدينة</label><input class="input" id="acity" value="${esc(x.city||'')}"></div><div class="field"><label>التنفيذ</label><select class="input" id="adm">${Object.entries(EX_DELIVERY).map(([k,v]) => `<option value="${k}" ${x.delivery_mode===k?'selected':''}>${v}</option>`).join('')}</select></div></div>
    <div class="grid2"><div class="field"><label>قيمة تقديرية</label><input class="input" id="av" type="number" min="0" step="50" value="${x.estimated_value??''}"></div><div class="field"><label>ملاحظات</label><input class="input" id="acond" maxlength="500" value="${esc(x.condition_note||'')}"></div></div></section></div>`, footer: '<button class="btn ghost" data-c>إلغاء</button><button class="btn primary" id="ask">حفظ التعديلات</button>' });
  $$('input[name="amode"]',m.root).forEach(r=>r.onchange=()=>$$('.choice',m.root).forEach(c=>c.classList.toggle('selected',c.querySelector('input')?.checked)));
  m.$('[data-c]').onclick=m.close;
  m.$('#ask').onclick=e=>busy(e.currentTarget,async()=>{ await api(`/admin/listings/${x.id}`,{method:'PATCH',body:{mode:m.root.querySelector('input[name="amode"]:checked')?.value,asset_type:m.$('#aa').value,title:m.$('#at').value.trim(),description:m.$('#ad').value.trim(),category_id:m.$('#ac').value||null,skill_id:m.$('#as').value||null,city:m.$('#acity').value.trim(),delivery_mode:m.$('#adm').value,estimated_value:m.$('#av').value?Number(m.$('#av').value):null,condition_note:m.$('#acond').value.trim()}}); toast('تم تعديل المنشور','ok'); m.close(); admListings(box); });
}

async function admListings(box) {
  const list = await get('/admin/listings');
  const statusMap = { published:['منشور','g'], paused:['متوقف','w'], closed:['مغلق','n'], removed:['محذوف','r'], draft:['مسودة','n'] };
  box.innerHTML = `<div class="admin-toolbar"><div><span class="eyebrow">EXCHANGE ENGINE</span><h2 style="margin:0">كل العروض والطلبات</h2></div><span class="muted small">${arNum(list.length)} منشور</span></div>${tbl(['المنشور','المالك','النوع','المدينة','العروض','الحالة','الإجراء'], list.map(x => `<tr><td><b>${esc(x.title)}</b><div class="xs muted">${x.mode==='offer'?'أقدّم':'أحتاج'} · ${esc(x.asset_type)}</div></td><td>${esc(x.owner_name)} ${x.owner_verified?verifiedBadge:''}<div class="xs muted">@${esc(x.owner_username)}</div></td><td>${esc(x.category_name || 'عام')}</td><td>${esc(x.city || '—')}</td><td>${arNum(x.proposals_count || 0)}</td><td>${chip(statusMap,x.status)}</td><td><div class="row gap-s wrap"><button class="btn sm ghost" data-le="${esc(x.id)}">${icon('edit')} تعديل</button><select class="input" data-lst="${esc(x.id)}" style="min-height:36px;padding:2px 8px;max-width:150px"><option value="">إجراء…</option><option value="published">نشر</option><option value="paused">إيقاف مؤقت</option><option value="closed">إغلاق</option><option value="removed">إزالة</option></select><button class="btn sm ghost" data-lf="${esc(x.id)}" data-f="${x.featured}" title="${x.featured?'إلغاء التمييز':'تمييز'}">${x.featured?'★ مميز':'☆ تمييز'}</button></div></td></tr>`), 'لا توجد عروض أو طلبات')}`;
  $$('[data-le]', box).forEach(b => { const x = list.find(v => String(v.id) === String(b.dataset.le)); if (x) b.onclick = () => adminListingEditor(x, box); });
  $$('[data-lst]', box).forEach(s => s.onchange = async () => { if (!s.value) return; const status=s.value; await api(`/admin/listings/${s.dataset.lst}/status`, { method:'PATCH', body:{status} }).catch(e=>toast(errMsg(e),'err')); admListings(box); });
  $$('[data-lf]', box).forEach(b => b.onclick = async () => { await api(`/admin/listings/${b.dataset.lf}/status`, { method:'PATCH', body:{ featured: b.dataset.f !== 'true' } }).catch(e=>toast(errMsg(e),'err')); admListings(box); });
}

/* ── jobs, skills, reviews, logs, settings ── */
async function admJobs(box) {
  const list = await get('/admin/jobs');
  box.innerHTML = tbl(['الفرصة', 'صاحبها', 'النوع', 'الحالة', 'التاريخ', ''], list.map(j => `<tr><td><b>${esc(j.title)}</b><div class="xs muted">${esc(j.company || '')}</div></td><td>${esc(j.owner_name)}</td><td>${L.jobType[j.job_type]}</td><td>${chip(L.job, j.status)}</td><td class="xs">${ago(j.created_at)}</td><td><select class="input" data-j="${esc(j.id)}" style="min-height:36px;padding:2px 8px"><option value="">إجراء…</option><option value="published">نشر</option><option value="rejected">رفض</option><option value="suspended">إيقاف</option><option value="closed">إغلاق</option></select></td></tr>`), 'لا توجد فرص');
  $$('[data-j]', box).forEach(s => s.onchange = async () => { if (!s.value) return; await api(`/admin/jobs/${s.dataset.j}/moderation`, { method: 'PATCH', body: { status: s.value } }).catch(e => toast(errMsg(e), 'err')); admJobs(box); });
}
async function admSkills(box) {
  const [skills, cats] = await Promise.all([get('/admin/skills'), get('/admin/categories')]);
  box.innerHTML = `<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(320px,1fr));align-items:start"><div class="card"><div class="row between"><h3 style="margin:0">التصنيفات</h3><button class="btn sm primary" id="nc">${icon('plus')}</button></div>${cats.map(c => `<div class="row between" style="padding:8px 0;border-bottom:1px solid var(--border)"><span>${esc(c.name)} <span class="xs muted">(${arNum(c.skill_count)})</span></span><span><button class="btn sm ghost" data-ec="${esc(c.id)}" data-n="${esc(c.name)}" aria-label="تعديل">${icon('edit')}</button><button class="btn sm ghost" data-dc="${esc(c.id)}" aria-label="حذف" style="color:var(--danger)">${icon('trash')}</button></span></div>`).join('')}</div>
    <div class="card"><div class="row between"><h3 style="margin:0">المهارات (${arNum(skills.length)})</h3><button class="btn sm primary" id="ns">${icon('plus')}</button></div>${skills.map(s => `<div class="row between" style="padding:8px 0;border-bottom:1px solid var(--border);${s.is_hidden ? 'opacity:.55' : ''}"><span>${esc(s.name)} <span class="xs muted">${esc(s.category || '')} · ${arNum(s.users)}</span></span><span class="row gap-s"><button class="btn sm ghost" data-hs="${esc(s.id)}" data-h="${s.is_hidden}" title="${s.is_hidden ? 'إظهار' : 'إخفاء'}">${icon(s.is_hidden ? 'eyeoff' : 'eye')}</button><button class="btn sm ghost" data-es="${esc(s.id)}" data-n="${esc(s.name)}" aria-label="تعديل">${icon('edit')}</button><button class="btn sm ghost" data-ds="${esc(s.id)}" aria-label="حذف" style="color:var(--danger)">${icon('trash')}</button></span></div>`).join('')}</div></div>`;
  const nameDialog = (title, cur, cb, extra = '') => { const m = openModal({ title, body: `<div class="field"><label for="nm">الاسم</label><input class="input" id="nm" maxlength="100" value="${esc(cur)}"></div>${extra}`, footer: '<button class="btn primary" id="ok">حفظ</button>' }); m.$('#ok').onclick = e => busy(e.currentTarget, async () => { await cb(m.$('#nm').value.trim(), m); m.close(); admSkills(box); }); };
  $('#nc').onclick = () => nameDialog('تصنيف جديد', '', n => api('/admin/categories', { method: 'POST', body: { name: n } }));
  $('#ns').onclick = () => nameDialog('مهارة جديدة', '', (n, m) => api('/admin/skills', { method: 'POST', body: { name: n, category_id: m.$('#sc').value || null } }), `<div class="field"><label for="sc">التصنيف</label><select class="input" id="sc"><option value="">—</option>${cats.map(c => `<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></div>`);
  $$('[data-ec]', box).forEach(b => b.onclick = () => nameDialog('تعديل التصنيف', b.dataset.n, n => api(`/admin/categories/${b.dataset.ec}`, { method: 'PATCH', body: { name: n } })));
  $$('[data-es]', box).forEach(b => b.onclick = () => nameDialog('تعديل المهارة', b.dataset.n, n => api(`/admin/skills/${b.dataset.es}`, { method: 'PATCH', body: { name: n } })));
  $$('[data-hs]', box).forEach(b => b.onclick = async () => { await api(`/admin/skills/${b.dataset.hs}`, { method: 'PATCH', body: { is_hidden: b.dataset.h !== 'true' } }); admSkills(box); });
  const del = (sel, path) => $$(sel, box).forEach(b => b.onclick = async () => { if (await confirmBox({ title: 'تأكيد الحذف', message: 'سيتم الحذف نهائيًا.', confirmText: 'حذف', danger: true })) { await api(`${path}/${Object.values(b.dataset)[0]}`, { method: 'DELETE' }).catch(e => toast(errMsg(e), 'err')); admSkills(box); } });
  del('[data-dc]', '/admin/categories'); del('[data-ds]', '/admin/skills');
}
async function admReviews(box) {
  const list = await get('/admin/reviews');
  box.innerHTML = tbl(['من', 'إلى', 'التقييم', 'التعليق', 'الحالة', ''], list.map(r => `<tr><td>${esc(r.reviewer_name)}</td><td>${esc(r.reviewee_name)}</td><td>${stars(r.rating)}</td><td class="small" style="max-width:320px">${esc(r.comment || '—')}</td><td>${chip({ active: ['ظاهر', 'g'], hidden: ['مخفي', 'n'] }, r.status)}</td><td><button class="btn sm ghost" data-r="${esc(r.id)}" data-s="${r.status === 'active' ? 'hidden' : 'active'}">${r.status === 'active' ? 'إخفاء' : 'إظهار'}</button></td></tr>`), 'لا توجد تقييمات');
  $$('[data-r]', box).forEach(b => b.onclick = async () => { await api(`/admin/reviews/${b.dataset.r}`, { method: 'PATCH', body: { status: b.dataset.s } }); admReviews(box); });
}
async function admLogs(box) {
  const list = await get('/admin/actions');
  box.innerHTML = tbl(['الإجراء', 'التفاصيل', 'بواسطة', 'المستهدف', 'الوقت'], list.map(l => `<tr><td><span class="chip">${ACTION_AR[l.action] || esc(l.action)}</span></td><td class="small">${esc(l.note)}</td><td>${esc(l.admin_name)}</td><td>${esc(l.target_user_name || '—')}</td><td class="xs">${fmtDate(l.created_at)} ${fmtTime(l.created_at)}</td></tr>`), 'لا توجد إجراءات');
}
async function admSettings(box) {
  const s = await get('/admin/settings');
  const sw = (k,t,d) => `<label class="feature-toggle card flat"><span class="toggle-copy"><b>${t}</b><small>${d}</small></span><input type="checkbox" data-k="${k}" ${s[k] ? 'checked' : ''}><span class="switch" aria-hidden="true"></span></label>`;
  box.innerHTML = `<div class="settings-hero card"><div><span class="eyebrow">PLATFORM CONTROL</span><h2>إدارة المنصة من غير تعديل الكود</h2><p class="muted">أي Feature Flag هنا يتخزن في السيرفر، والواجهات تعتمد عليه. استخدمه لتجربة خصائص جديدة أو إيقافها فورًا.</p></div><span class="chip">SUPER CONTROL</span></div>
  <div class="settings-layout"><section class="card"><h3>الهوية والسلوك</h3><div class="field"><label for="pn">اسم المنصة</label><input class="input" id="pn" value="${esc(s.platform_name)}" maxlength="60"></div><div class="grid2"><div class="field"><label for="m1">حد طلبات التبادل يوميًا</label><input class="input" id="m1" type="number" min="1" max="500" value="${s.max_exchange_requests_day}"></div><div class="field"><label for="m2">حد طلبات التواصل يوميًا</label><input class="input" id="m2" type="number" min="1" max="500" value="${s.max_connection_requests_day}"></div></div><button class="btn primary" id="sv">حفظ كل الإعدادات</button></section><section class="feature-list"><h3>Feature Flags</h3>${sw('registration_enabled','التسجيل','السماح بإنشاء حسابات جديدة')}${sw('exchange_engine_enabled','محرك التبادل','العروض والطلبات العامة')}${sw('skills_exchange_enabled','تبادل المهارات','نوع مهارات')}${sw('services_exchange_enabled','تبادل الخدمات','نوع الخدمات')}${sw('products_exchange_enabled','تبادل المنتجات','نوع الأشياء والمنتجات')}${sw('time_exchange_enabled','تبادل الوقت','مساعدة أو وقت مقابل وقت')}${sw('knowledge_exchange_enabled','تبادل المعرفة','جلسات وخبرات ومعرفة')}${sw('paid_deals_enabled','التبادل المدفوع','إظهار صفقات الدفع بجانب التبادل')}${sw('advertising_enabled','الإعلانات','عرض إعلانات الشركاء')}${sw('assistant_enabled','المساعد الذكي','Khod & Hat AI')}${sw('verification_enabled','التوثيق','تشغيل مسار توثيق الحسابات')}${sw('connections_enabled','طلبات التواصل','السماح بإنشاء طلبات تواصل')}${sw('chat_enabled','المحادثات','تشغيل محادثات المستخدمين')}${sw('exchanges_enabled','التبادلات القديمة','طلبات التبادل المباشر بالمهارات')}${sw('reviews_enabled','التقييمات','السماح بالتقييم بعد اكتمال التبادل')}${sw('jobs_enabled','الوظائف','إنشاء فرص ووظائف جديدة')}</section></div>`;
  $('#sv').onclick = e => busy(e.currentTarget, async () => { const body = { platform_name: $('#pn').value.trim(), max_exchange_requests_day:Number($('#m1').value), max_connection_requests_day:Number($('#m2').value) }; $$('[data-k]', box).forEach(c => body[c.dataset.k]=c.checked); await api('/admin/settings',{method:'PATCH',body}); toast('تم حفظ إعدادات المنصة','ok'); });
}
